// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: IfThirdVideoIntercom.proto

package com.intellif.ifai.thirdVideoIntercom;

/**
 * Protobuf enum {@code Ifaipb.AnswerType}
 */
public enum AnswerType
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <pre>
   * 未知
   * </pre>
   *
   * <code>UN_KNOW_TYPE = 0;</code>
   */
  UN_KNOW_TYPE(0),
  /**
   * <pre>
   *  手机接听
   * </pre>
   *
   * <code>APP = 1;</code>
   */
  APP(1),
  /**
   * <pre>
   *  WEB接听
   * </pre>
   *
   * <code>WEB = 2;</code>
   */
  WEB(2),
  /**
   * <pre>
   *  PAD接听
   * </pre>
   *
   * <code>PAD = 3;</code>
   */
  PAD(3),
  /**
   * <pre>
   *  室内机接听
   * </pre>
   *
   * <code>ROOM = 4;</code>
   */
  ROOM(4),
  UNRECOGNIZED(-1),
  ;

  /**
   * <pre>
   * 未知
   * </pre>
   *
   * <code>UN_KNOW_TYPE = 0;</code>
   */
  public static final int UN_KNOW_TYPE_VALUE = 0;
  /**
   * <pre>
   *  手机接听
   * </pre>
   *
   * <code>APP = 1;</code>
   */
  public static final int APP_VALUE = 1;
  /**
   * <pre>
   *  WEB接听
   * </pre>
   *
   * <code>WEB = 2;</code>
   */
  public static final int WEB_VALUE = 2;
  /**
   * <pre>
   *  PAD接听
   * </pre>
   *
   * <code>PAD = 3;</code>
   */
  public static final int PAD_VALUE = 3;
  /**
   * <pre>
   *  室内机接听
   * </pre>
   *
   * <code>ROOM = 4;</code>
   */
  public static final int ROOM_VALUE = 4;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @Deprecated
  public static AnswerType valueOf(int value) {
    return forNumber(value);
  }

  public static AnswerType forNumber(int value) {
    switch (value) {
      case 0: return UN_KNOW_TYPE;
      case 1: return APP;
      case 2: return WEB;
      case 3: return PAD;
      case 4: return ROOM;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<AnswerType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      AnswerType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<AnswerType>() {
          public AnswerType findValueByNumber(int number) {
            return AnswerType.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return Ifai.getDescriptor().getEnumTypes().get(1);
  }

  private static final AnswerType[] VALUES = values();

  public static AnswerType valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private AnswerType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:Ifaipb.AnswerType)
}

