// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: IfDeviceManagment.proto

package com.intellif.ifai.devmgmt;

public interface LoginResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Ifaipb.LoginResponse)
    com.google.protobuf.MessageOrBuilder {
}
