// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: IfDeviceManagment.proto

package com.intellif.ifai.devmgmt;

public interface SetNetworkConfigurationRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Ifaipb.SetNetworkConfigurationRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .Ifaipb.NetworkConfiguration configuration = 1;</code>
   */
  java.util.List<com.intellif.ifai.devmgmt.NetworkConfiguration> 
      getConfigurationList();
  /**
   * <code>repeated .Ifaipb.NetworkConfiguration configuration = 1;</code>
   */
  com.intellif.ifai.devmgmt.NetworkConfiguration getConfiguration(int index);
  /**
   * <code>repeated .Ifaipb.NetworkConfiguration configuration = 1;</code>
   */
  int getConfigurationCount();
  /**
   * <code>repeated .Ifaipb.NetworkConfiguration configuration = 1;</code>
   */
  java.util.List<? extends com.intellif.ifai.devmgmt.NetworkConfigurationOrBuilder> 
      getConfigurationOrBuilderList();
  /**
   * <code>repeated .Ifaipb.NetworkConfiguration configuration = 1;</code>
   */
  com.intellif.ifai.devmgmt.NetworkConfigurationOrBuilder getConfigurationOrBuilder(
      int index);
}
