// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: IfDoorControlConfiguration.proto

package com.intellif.ifai.config;

public final class Ifai {
  private Ifai() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Ifaipb_SetDoorControlConfigurationRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Ifaipb_SetDoorControlConfigurationRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Ifaipb_SetDoorControlConfigurationResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Ifaipb_SetDoorControlConfigurationResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Ifaipb_SetDoorControlFeatureConfigurationRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Ifaipb_SetDoorControlFeatureConfigurationRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Ifaipb_SetDoorControlFeatureConfigurationResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Ifaipb_SetDoorControlFeatureConfigurationResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Ifaipb_GetDoorControlConfigurationRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Ifaipb_GetDoorControlConfigurationRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Ifaipb_GetDoorControlConfigurationResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Ifaipb_GetDoorControlConfigurationResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Ifaipb_DoorControlConfiguration_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Ifaipb_DoorControlConfiguration_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Ifaipb_DoorControlAlgConfiguration_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Ifaipb_DoorControlAlgConfiguration_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Ifaipb_DoorInfraredConfiguration_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Ifaipb_DoorInfraredConfiguration_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Ifaipb_DoorControlFeatureConfiguration_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Ifaipb_DoorControlFeatureConfiguration_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Ifaipb_DoorControlAlgFeatureConfiguration_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Ifaipb_DoorControlAlgFeatureConfiguration_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Ifaipb_DoorInfraredFeatureConfiguration_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Ifaipb_DoorInfraredFeatureConfiguration_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Ifaipb_OpenDoorSignalRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Ifaipb_OpenDoorSignalRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Ifaipb_OpenDoorSignalResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Ifaipb_OpenDoorSignalResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Ifaipb_SetROIRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Ifaipb_SetROIRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Ifaipb_SetROIResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Ifaipb_SetROIResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Ifaipb_GetROIRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Ifaipb_GetROIRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Ifaipb_GetROIResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Ifaipb_GetROIResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Ifaipb_SetDoorOtherConfigurationRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Ifaipb_SetDoorOtherConfigurationRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Ifaipb_SetDoorOtherConfigurationResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Ifaipb_SetDoorOtherConfigurationResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Ifaipb_GetDoorOtherConfigurationRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Ifaipb_GetDoorOtherConfigurationRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Ifaipb_GetDoorOtherConfigurationResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Ifaipb_GetDoorOtherConfigurationResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Ifaipb_DoorOtherConfiguration_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Ifaipb_DoorOtherConfiguration_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Ifaipb_SetPlatformConfigurationRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Ifaipb_SetPlatformConfigurationRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Ifaipb_SetPlatformConfigurationResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Ifaipb_SetPlatformConfigurationResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Ifaipb_GetPlatformConfigurationRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Ifaipb_GetPlatformConfigurationRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Ifaipb_GetPlatformConfigurationResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Ifaipb_GetPlatformConfigurationResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Ifaipb_PlatformConfiguration_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Ifaipb_PlatformConfiguration_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Ifaipb_SetNetRelayConfigurationRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Ifaipb_SetNetRelayConfigurationRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Ifaipb_SetNetRelayConfigurationResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Ifaipb_SetNetRelayConfigurationResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Ifaipb_GetNetRelayConfigurationRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Ifaipb_GetNetRelayConfigurationRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Ifaipb_GetNetRelayConfigurationResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Ifaipb_GetNetRelayConfigurationResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Ifaipb_NetRelayConfiguration_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Ifaipb_NetRelayConfiguration_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Ifaipb_OpenDoorSignalExRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Ifaipb_OpenDoorSignalExRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Ifaipb_OpenDoorSignalExRequest_TemperatureInformation_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Ifaipb_OpenDoorSignalExRequest_TemperatureInformation_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Ifaipb_OpenDoorSignalExResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Ifaipb_OpenDoorSignalExResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n IfDoorControlConfiguration.proto\022\006Ifai" +
      "pb\032\022IfCommonType.proto\"\377\001\n\"SetDoorContro" +
      "lConfigurationRequest\022K\n\036door_control_al" +
      "g_configuration\030\001 \001(\0132#.Ifaipb.DoorContr" +
      "olAlgConfiguration\022D\n\032door_control_confi" +
      "guration\030\002 \001(\0132 .Ifaipb.DoorControlConfi" +
      "guration\022F\n\033door_infrared_configuration\030" +
      "\003 \001(\0132!.Ifaipb.DoorInfraredConfiguration" +
      "\"%\n#SetDoorControlConfigurationResponse\"" +
      "\233\002\n)SetDoorControlFeatureConfigurationRe" +
      "quest\022R\n\036door_control_alg_configuration\030" +
      "\001 \001(\0132*.Ifaipb.DoorControlAlgFeatureConf" +
      "iguration\022K\n\032door_control_configuration\030" +
      "\002 \001(\0132\'.Ifaipb.DoorControlFeatureConfigu" +
      "ration\022M\n\033door_infrared_configuration\030\003 " +
      "\001(\0132(.Ifaipb.DoorInfraredFeatureConfigur" +
      "ation\",\n*SetDoorControlFeatureConfigurat" +
      "ionResponse\"$\n\"GetDoorControlConfigurati" +
      "onRequest\"\200\002\n#GetDoorControlConfiguratio" +
      "nResponse\022K\n\036door_control_alg_configurat" +
      "ion\030\001 \001(\0132#.Ifaipb.DoorControlAlgConfigu" +
      "ration\022D\n\032door_control_configuration\030\002 \001" +
      "(\0132 .Ifaipb.DoorControlConfiguration\022F\n\033" +
      "door_infrared_configuration\030\003 \001(\0132!.Ifai" +
      "pb.DoorInfraredConfiguration\"\266\002\n\030DoorCon" +
      "trolConfiguration\0224\n\022pass_through_model\030" +
      "\001 \001(\0132\030.Ifaipb.PassThroughModel\0224\n\022door_" +
      "control_model\030\002 \001(\0162\030.Ifaipb.DoorControl" +
      "Model\022\027\n\017signal_duration\030\003 \001(\005\022\024\n\014voice_" +
      "prompt\030\004 \001(\010\022\024\n\014fixed_prompt\030\005 \001(\t\022\033\n\004lo" +
      "go\030\006 \001(\0132\r.Ifaipb.Image\022\022\n\nvoice_file\030\007 " +
      "\001(\014\022\020\n\010password\030\010 \001(\t\022\021\n\tover_time\030\t \001(\005" +
      "\022\023\n\013enabled_pwd\030\n \001(\010\"\212\002\n\033DoorControlAlg" +
      "Configuration\022\027\n\017infrared_living\030\001 \001(\010\022\022" +
      "\n\nrgb_living\030\002 \001(\010\022\"\n\032similarity_score_t" +
      "hreshold\030\003 \001(\002\022\037\n\027quality_score_threshol" +
      "d\030\004 \001(\002\022\037\n\005pitch\030\005 \001(\0132\020.Ifaipb.IntRange" +
      "\022\035\n\003yaw\030\006 \001(\0132\020.Ifaipb.IntRange\022\036\n\004roll\030" +
      "\007 \001(\0132\020.Ifaipb.IntRange\022\031\n\021respirator_sw" +
      "itch\030\010 \001(\010\"\261\001\n\031DoorInfraredConfiguration" +
      "\022#\n\033infrared_temperature_switch\030\001 \001(\010\022$\n" +
      "\034infrared_temperature_minimum\030\002 \001(\002\022$\n\034i" +
      "nfrared_temperature_maximum\030\003 \001(\002\022#\n\033inf" +
      "rared_temperature_adjust\030\004 \001(\002\"\320\003\n\037DoorC" +
      "ontrolFeatureConfiguration\022;\n\022pass_throu" +
      "gh_model\030\001 \001(\0132\037.Ifaipb.PassThroughFeatu" +
      "reModel\0224\n\022door_control_model\030\002 \001(\0162\030.If" +
      "aipb.DoorControlModel\022*\n\017signal_duration" +
      "\030\003 \001(\0132\021.Ifaipb.CommonInt\022(\n\014voice_promp" +
      "t\030\004 \001(\0132\022.Ifaipb.CommonBool\022*\n\014fixed_pro" +
      "mpt\030\005 \001(\0132\024.Ifaipb.CommonString\022\033\n\004logo\030" +
      "\006 \001(\0132\r.Ifaipb.Image\022\'\n\nvoice_file\030\007 \001(\013" +
      "2\023.Ifaipb.CommonBytes\022#\n\010password\030\010 \001(\0132" +
      "\021.Ifaipb.CommonInt\022$\n\tover_time\030\t \001(\0132\021." +
      "Ifaipb.CommonInt\022\'\n\013enabled_pwd\030\n \001(\0132\022." +
      "Ifaipb.CommonBool\"\367\002\n\"DoorControlAlgFeat" +
      "ureConfiguration\022+\n\017infrared_living\030\001 \001(" +
      "\0132\022.Ifaipb.CommonBool\022&\n\nrgb_living\030\002 \001(" +
      "\0132\022.Ifaipb.CommonBool\0227\n\032similarity_scor" +
      "e_threshold\030\003 \001(\0132\023.Ifaipb.CommonFloat\0224" +
      "\n\027quality_score_threshold\030\004 \001(\0132\023.Ifaipb" +
      ".CommonFloat\022\037\n\005pitch\030\005 \001(\0132\020.Ifaipb.Int" +
      "Range\022\035\n\003yaw\030\006 \001(\0132\020.Ifaipb.IntRange\022\036\n\004" +
      "roll\030\007 \001(\0132\020.Ifaipb.IntRange\022-\n\021respirat" +
      "or_switch\030\010 \001(\0132\022.Ifaipb.CommonBool\"\213\002\n " +
      "DoorInfraredFeatureConfiguration\0227\n\033infr" +
      "ared_temperature_switch\030\001 \001(\0132\022.Ifaipb.C" +
      "ommonBool\0229\n\034infrared_temperature_minimu" +
      "m\030\002 \001(\0132\023.Ifaipb.CommonFloat\0229\n\034infrared" +
      "_temperature_maximum\030\003 \001(\0132\023.Ifaipb.Comm" +
      "onFloat\0228\n\033infrared_temperature_adjust\030\004" +
      " \001(\0132\023.Ifaipb.CommonFloat\"\027\n\025OpenDoorSig" +
      "nalRequest\"\030\n\026OpenDoorSignalResponse\"1\n\r" +
      "SetROIRequest\022 \n\005rects\030\001 \003(\0132\021.Ifaipb.Re" +
      "ctangle\"\020\n\016SetROIResponse\"\017\n\rGetROIReque" +
      "st\"2\n\016GetROIResponse\022 \n\005rects\030\001 \003(\0132\021.If" +
      "aipb.Rectangle\"d\n SetDoorOtherConfigurat" +
      "ionRequest\022@\n\030door_other_configuration\030\001" +
      " \001(\0132\036.Ifaipb.DoorOtherConfiguration\"#\n!" +
      "SetDoorOtherConfigurationResponse\"\"\n Get" +
      "DoorOtherConfigurationRequest\"e\n!GetDoor" +
      "OtherConfigurationResponse\022@\n\030door_other" +
      "_configuration\030\001 \001(\0132\036.Ifaipb.DoorOtherC" +
      "onfiguration\"\337\004\n\026DoorOtherConfiguration\022" +
      "\027\n\017whiteLight_mode\030\001 \001(\005\022+\n\017whiteLight_t" +
      "ime\030\002 \001(\0132\022.Ifaipb.TimePeriod\022\016\n\006volume\030" +
      "\003 \001(\005\022\032\n\022liveness_threshold\030\004 \001(\002\022\031\n\021qua" +
      "lity_threshold\030\005 \001(\002\022\023\n\013minFaceSize\030\006 \001(" +
      "\005\022\023\n\013maxFaceSize\030\007 \001(\005\022\025\n\rrecogInterval\030" +
      "\010 \001(\005\022\025\n\rstrangerTimes\030\t \001(\005\022\023\n\013saveOffl" +
      "ine\030\n \001(\010\022\025\n\rpicUploadType\030\013 \001(\005\022\023\n\013hExp" +
      "andCoff\030\014 \001(\005\022\023\n\013vExpandCoff\030\r \001(\005\022\022\n\npi" +
      "cQuality\030\016 \001(\005\022\023\n\013nameShowWay\030\017 \001(\005\022\024\n\014w" +
      "ifi_account\030\020 \001(\t\022\023\n\013wifi_passwd\030\021 \001(\t\022\020" +
      "\n\010language\030\022 \001(\005\022\030\n\020qrCodeDeviceType\030\023 \001" +
      "(\005\022\031\n\021successVoiceStyle\030\024 \001(\005\022\030\n\020success" +
      "ShowStyle\030\025 \001(\005\022\024\n\014faceRectRate\030\026 \001(\005\022\023\n" +
      "\013picNoiseDet\030\027 \001(\010\022\023\n\013facePoseDet\030\030 \001(\010\022" +
      "\025\n\rregWithNoMask\030\031 \001(\010\"V\n\037SetPlatformCon" +
      "figurationRequest\0223\n\014platformInfo\030\001 \001(\0132" +
      "\035.Ifaipb.PlatformConfiguration\"\"\n SetPla" +
      "tformConfigurationResponse\"!\n\037GetPlatfor" +
      "mConfigurationRequest\"i\n GetPlatformConf" +
      "igurationResponse\0223\n\014platformInfo\030\001 \001(\0132" +
      "\035.Ifaipb.PlatformConfiguration\022\020\n\010isOnli" +
      "ne\030\002 \001(\010\"Z\n\025PlatformConfiguration\022\020\n\010hos" +
      "tname\030\001 \001(\t\022\014\n\004port\030\002 \001(\005\022\017\n\007account\030\003 \001" +
      "(\t\022\020\n\010password\030\004 \001(\t\"U\n\037SetNetRelayConfi" +
      "gurationRequest\0222\n\013netRelayCfg\030\001 \001(\0132\035.I" +
      "faipb.NetRelayConfiguration\"\"\n SetNetRel" +
      "ayConfigurationResponse\"!\n\037GetNetRelayCo" +
      "nfigurationRequest\"V\n GetNetRelayConfigu" +
      "rationResponse\0222\n\013netRelayCfg\030\001 \001(\0132\035.If" +
      "aipb.NetRelayConfiguration\"7\n\025NetRelayCo" +
      "nfiguration\022\r\n\005devip\030\001 \001(\t\022\017\n\007outport\030\002 " +
      "\001(\005\"\244\002\n\027OpenDoorSignalExRequest\022\021\n\topen_" +
      "door\030\001 \001(\005\022K\n\013temperature\030\002 \001(\01326.Ifaipb" +
      ".OpenDoorSignalExRequest.TemperatureInfo" +
      "rmation\022\014\n\004name\030\003 \001(\t\022\023\n\013work_number\030\004 \001" +
      "(\t\022\013\n\003tip\030\005 \001(\t\022\036\n\005image\030\006 \001(\0132\r.Ifaipb." +
      "ImageH\000\022\023\n\timage_url\030\007 \001(\tH\000\0326\n\026Temperat" +
      "ureInformation\022\r\n\005state\030\001 \001(\005\022\r\n\005value\030\002" +
      " \001(\002B\014\n\nimage_type\"\032\n\030OpenDoorSignalExRe" +
      "sponse2\263\003\n\035GuardPassConfigurationService" +
      "\022t\n\031SetGuardPassConfiguration\022*.Ifaipb.S" +
      "etDoorControlConfigurationRequest\032+.Ifai" +
      "pb.SetDoorControlConfigurationResponse\022t" +
      "\n\031GetGuardPassConfiguration\022*.Ifaipb.Get" +
      "DoorControlConfigurationRequest\032+.Ifaipb" +
      ".GetDoorControlConfigurationResponse\022O\n\016" +
      "OpenDoorSignal\022\035.Ifaipb.OpenDoorSignalRe" +
      "quest\032\036.Ifaipb.OpenDoorSignalResponse\022U\n" +
      "\020OpenDoorExSignal\022\037.Ifaipb.OpenDoorSigna" +
      "lExRequest\032 .Ifaipb.OpenDoorSignalExResp" +
      "onseB)\n\030com.intellif.ifai.configB\004IfaiP\001" +
      "\242\002\004Ifaib\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.intellif.ifai.common.Ifai.getDescriptor(),
        }, assigner);
    internal_static_Ifaipb_SetDoorControlConfigurationRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Ifaipb_SetDoorControlConfigurationRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Ifaipb_SetDoorControlConfigurationRequest_descriptor,
        new java.lang.String[] { "DoorControlAlgConfiguration", "DoorControlConfiguration", "DoorInfraredConfiguration", });
    internal_static_Ifaipb_SetDoorControlConfigurationResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Ifaipb_SetDoorControlConfigurationResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Ifaipb_SetDoorControlConfigurationResponse_descriptor,
        new java.lang.String[] { });
    internal_static_Ifaipb_SetDoorControlFeatureConfigurationRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_Ifaipb_SetDoorControlFeatureConfigurationRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Ifaipb_SetDoorControlFeatureConfigurationRequest_descriptor,
        new java.lang.String[] { "DoorControlAlgConfiguration", "DoorControlConfiguration", "DoorInfraredConfiguration", });
    internal_static_Ifaipb_SetDoorControlFeatureConfigurationResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_Ifaipb_SetDoorControlFeatureConfigurationResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Ifaipb_SetDoorControlFeatureConfigurationResponse_descriptor,
        new java.lang.String[] { });
    internal_static_Ifaipb_GetDoorControlConfigurationRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_Ifaipb_GetDoorControlConfigurationRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Ifaipb_GetDoorControlConfigurationRequest_descriptor,
        new java.lang.String[] { });
    internal_static_Ifaipb_GetDoorControlConfigurationResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_Ifaipb_GetDoorControlConfigurationResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Ifaipb_GetDoorControlConfigurationResponse_descriptor,
        new java.lang.String[] { "DoorControlAlgConfiguration", "DoorControlConfiguration", "DoorInfraredConfiguration", });
    internal_static_Ifaipb_DoorControlConfiguration_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_Ifaipb_DoorControlConfiguration_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Ifaipb_DoorControlConfiguration_descriptor,
        new java.lang.String[] { "PassThroughModel", "DoorControlModel", "SignalDuration", "VoicePrompt", "FixedPrompt", "Logo", "VoiceFile", "Password", "OverTime", "EnabledPwd", });
    internal_static_Ifaipb_DoorControlAlgConfiguration_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_Ifaipb_DoorControlAlgConfiguration_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Ifaipb_DoorControlAlgConfiguration_descriptor,
        new java.lang.String[] { "InfraredLiving", "RgbLiving", "SimilarityScoreThreshold", "QualityScoreThreshold", "Pitch", "Yaw", "Roll", "RespiratorSwitch", });
    internal_static_Ifaipb_DoorInfraredConfiguration_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_Ifaipb_DoorInfraredConfiguration_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Ifaipb_DoorInfraredConfiguration_descriptor,
        new java.lang.String[] { "InfraredTemperatureSwitch", "InfraredTemperatureMinimum", "InfraredTemperatureMaximum", "InfraredTemperatureAdjust", });
    internal_static_Ifaipb_DoorControlFeatureConfiguration_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_Ifaipb_DoorControlFeatureConfiguration_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Ifaipb_DoorControlFeatureConfiguration_descriptor,
        new java.lang.String[] { "PassThroughModel", "DoorControlModel", "SignalDuration", "VoicePrompt", "FixedPrompt", "Logo", "VoiceFile", "Password", "OverTime", "EnabledPwd", });
    internal_static_Ifaipb_DoorControlAlgFeatureConfiguration_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_Ifaipb_DoorControlAlgFeatureConfiguration_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Ifaipb_DoorControlAlgFeatureConfiguration_descriptor,
        new java.lang.String[] { "InfraredLiving", "RgbLiving", "SimilarityScoreThreshold", "QualityScoreThreshold", "Pitch", "Yaw", "Roll", "RespiratorSwitch", });
    internal_static_Ifaipb_DoorInfraredFeatureConfiguration_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_Ifaipb_DoorInfraredFeatureConfiguration_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Ifaipb_DoorInfraredFeatureConfiguration_descriptor,
        new java.lang.String[] { "InfraredTemperatureSwitch", "InfraredTemperatureMinimum", "InfraredTemperatureMaximum", "InfraredTemperatureAdjust", });
    internal_static_Ifaipb_OpenDoorSignalRequest_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_Ifaipb_OpenDoorSignalRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Ifaipb_OpenDoorSignalRequest_descriptor,
        new java.lang.String[] { });
    internal_static_Ifaipb_OpenDoorSignalResponse_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_Ifaipb_OpenDoorSignalResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Ifaipb_OpenDoorSignalResponse_descriptor,
        new java.lang.String[] { });
    internal_static_Ifaipb_SetROIRequest_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_Ifaipb_SetROIRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Ifaipb_SetROIRequest_descriptor,
        new java.lang.String[] { "Rects", });
    internal_static_Ifaipb_SetROIResponse_descriptor =
      getDescriptor().getMessageTypes().get(15);
    internal_static_Ifaipb_SetROIResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Ifaipb_SetROIResponse_descriptor,
        new java.lang.String[] { });
    internal_static_Ifaipb_GetROIRequest_descriptor =
      getDescriptor().getMessageTypes().get(16);
    internal_static_Ifaipb_GetROIRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Ifaipb_GetROIRequest_descriptor,
        new java.lang.String[] { });
    internal_static_Ifaipb_GetROIResponse_descriptor =
      getDescriptor().getMessageTypes().get(17);
    internal_static_Ifaipb_GetROIResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Ifaipb_GetROIResponse_descriptor,
        new java.lang.String[] { "Rects", });
    internal_static_Ifaipb_SetDoorOtherConfigurationRequest_descriptor =
      getDescriptor().getMessageTypes().get(18);
    internal_static_Ifaipb_SetDoorOtherConfigurationRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Ifaipb_SetDoorOtherConfigurationRequest_descriptor,
        new java.lang.String[] { "DoorOtherConfiguration", });
    internal_static_Ifaipb_SetDoorOtherConfigurationResponse_descriptor =
      getDescriptor().getMessageTypes().get(19);
    internal_static_Ifaipb_SetDoorOtherConfigurationResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Ifaipb_SetDoorOtherConfigurationResponse_descriptor,
        new java.lang.String[] { });
    internal_static_Ifaipb_GetDoorOtherConfigurationRequest_descriptor =
      getDescriptor().getMessageTypes().get(20);
    internal_static_Ifaipb_GetDoorOtherConfigurationRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Ifaipb_GetDoorOtherConfigurationRequest_descriptor,
        new java.lang.String[] { });
    internal_static_Ifaipb_GetDoorOtherConfigurationResponse_descriptor =
      getDescriptor().getMessageTypes().get(21);
    internal_static_Ifaipb_GetDoorOtherConfigurationResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Ifaipb_GetDoorOtherConfigurationResponse_descriptor,
        new java.lang.String[] { "DoorOtherConfiguration", });
    internal_static_Ifaipb_DoorOtherConfiguration_descriptor =
      getDescriptor().getMessageTypes().get(22);
    internal_static_Ifaipb_DoorOtherConfiguration_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Ifaipb_DoorOtherConfiguration_descriptor,
        new java.lang.String[] { "WhiteLightMode", "WhiteLightTime", "Volume", "LivenessThreshold", "QualityThreshold", "MinFaceSize", "MaxFaceSize", "RecogInterval", "StrangerTimes", "SaveOffline", "PicUploadType", "HExpandCoff", "VExpandCoff", "PicQuality", "NameShowWay", "WifiAccount", "WifiPasswd", "Language", "QrCodeDeviceType", "SuccessVoiceStyle", "SuccessShowStyle", "FaceRectRate", "PicNoiseDet", "FacePoseDet", "RegWithNoMask", });
    internal_static_Ifaipb_SetPlatformConfigurationRequest_descriptor =
      getDescriptor().getMessageTypes().get(23);
    internal_static_Ifaipb_SetPlatformConfigurationRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Ifaipb_SetPlatformConfigurationRequest_descriptor,
        new java.lang.String[] { "PlatformInfo", });
    internal_static_Ifaipb_SetPlatformConfigurationResponse_descriptor =
      getDescriptor().getMessageTypes().get(24);
    internal_static_Ifaipb_SetPlatformConfigurationResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Ifaipb_SetPlatformConfigurationResponse_descriptor,
        new java.lang.String[] { });
    internal_static_Ifaipb_GetPlatformConfigurationRequest_descriptor =
      getDescriptor().getMessageTypes().get(25);
    internal_static_Ifaipb_GetPlatformConfigurationRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Ifaipb_GetPlatformConfigurationRequest_descriptor,
        new java.lang.String[] { });
    internal_static_Ifaipb_GetPlatformConfigurationResponse_descriptor =
      getDescriptor().getMessageTypes().get(26);
    internal_static_Ifaipb_GetPlatformConfigurationResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Ifaipb_GetPlatformConfigurationResponse_descriptor,
        new java.lang.String[] { "PlatformInfo", "IsOnline", });
    internal_static_Ifaipb_PlatformConfiguration_descriptor =
      getDescriptor().getMessageTypes().get(27);
    internal_static_Ifaipb_PlatformConfiguration_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Ifaipb_PlatformConfiguration_descriptor,
        new java.lang.String[] { "Hostname", "Port", "Account", "Password", });
    internal_static_Ifaipb_SetNetRelayConfigurationRequest_descriptor =
      getDescriptor().getMessageTypes().get(28);
    internal_static_Ifaipb_SetNetRelayConfigurationRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Ifaipb_SetNetRelayConfigurationRequest_descriptor,
        new java.lang.String[] { "NetRelayCfg", });
    internal_static_Ifaipb_SetNetRelayConfigurationResponse_descriptor =
      getDescriptor().getMessageTypes().get(29);
    internal_static_Ifaipb_SetNetRelayConfigurationResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Ifaipb_SetNetRelayConfigurationResponse_descriptor,
        new java.lang.String[] { });
    internal_static_Ifaipb_GetNetRelayConfigurationRequest_descriptor =
      getDescriptor().getMessageTypes().get(30);
    internal_static_Ifaipb_GetNetRelayConfigurationRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Ifaipb_GetNetRelayConfigurationRequest_descriptor,
        new java.lang.String[] { });
    internal_static_Ifaipb_GetNetRelayConfigurationResponse_descriptor =
      getDescriptor().getMessageTypes().get(31);
    internal_static_Ifaipb_GetNetRelayConfigurationResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Ifaipb_GetNetRelayConfigurationResponse_descriptor,
        new java.lang.String[] { "NetRelayCfg", });
    internal_static_Ifaipb_NetRelayConfiguration_descriptor =
      getDescriptor().getMessageTypes().get(32);
    internal_static_Ifaipb_NetRelayConfiguration_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Ifaipb_NetRelayConfiguration_descriptor,
        new java.lang.String[] { "Devip", "Outport", });
    internal_static_Ifaipb_OpenDoorSignalExRequest_descriptor =
      getDescriptor().getMessageTypes().get(33);
    internal_static_Ifaipb_OpenDoorSignalExRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Ifaipb_OpenDoorSignalExRequest_descriptor,
        new java.lang.String[] { "OpenDoor", "Temperature", "Name", "WorkNumber", "Tip", "Image", "ImageUrl", "ImageType", });
    internal_static_Ifaipb_OpenDoorSignalExRequest_TemperatureInformation_descriptor =
      internal_static_Ifaipb_OpenDoorSignalExRequest_descriptor.getNestedTypes().get(0);
    internal_static_Ifaipb_OpenDoorSignalExRequest_TemperatureInformation_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Ifaipb_OpenDoorSignalExRequest_TemperatureInformation_descriptor,
        new java.lang.String[] { "State", "Value", });
    internal_static_Ifaipb_OpenDoorSignalExResponse_descriptor =
      getDescriptor().getMessageTypes().get(34);
    internal_static_Ifaipb_OpenDoorSignalExResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Ifaipb_OpenDoorSignalExResponse_descriptor,
        new java.lang.String[] { });
    com.intellif.ifai.common.Ifai.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
