// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: IfDoorControlConfiguration.proto

package com.intellif.ifai.config;

public interface SetDoorControlConfigurationResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Ifaipb.SetDoorControlConfigurationResponse)
    com.google.protobuf.MessageOrBuilder {
}
