// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: IfDoorControlConfiguration.proto

package com.intellif.ifai.config;

public interface SetDoorOtherConfigurationRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Ifaipb.SetDoorOtherConfigurationRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *门禁其他配置 20200515 test    
   * </pre>
   *
   * <code>.Ifaipb.DoorOtherConfiguration door_other_configuration = 1;</code>
   */
  boolean hasDoorOtherConfiguration();
  /**
   * <pre>
   *门禁其他配置 20200515 test    
   * </pre>
   *
   * <code>.Ifaipb.DoorOtherConfiguration door_other_configuration = 1;</code>
   */
  com.intellif.ifai.config.DoorOtherConfiguration getDoorOtherConfiguration();
  /**
   * <pre>
   *门禁其他配置 20200515 test    
   * </pre>
   *
   * <code>.Ifaipb.DoorOtherConfiguration door_other_configuration = 1;</code>
   */
  com.intellif.ifai.config.DoorOtherConfigurationOrBuilder getDoorOtherConfigurationOrBuilder();
}
