// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: IfPadVideoIntercom.proto

package com.intellif.ifai.padVideoIntercom;

/**
 * <pre>
 *平台通知平板接听呼叫请求
 * </pre>
 *
 * Protobuf type {@code Ifaipb.CallPadRequest}
 */
public  final class CallPadRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:Ifaipb.CallPadRequest)
    CallPadRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use CallPadRequest.newBuilder() to construct.
  private CallPadRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CallPadRequest() {
    captureId_ = "";
    deviceId_ = "";
    deviceName_ = "";
    deviceLoc_ = "";
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private CallPadRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            com.intellif.ifai.common.CommonInt.Builder subBuilder = null;
            if (recordId_ != null) {
              subBuilder = recordId_.toBuilder();
            }
            recordId_ = input.readMessage(com.intellif.ifai.common.CommonInt.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(recordId_);
              recordId_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            String s = input.readStringRequireUtf8();

            captureId_ = s;
            break;
          }
          case 26: {
            String s = input.readStringRequireUtf8();

            deviceId_ = s;
            break;
          }
          case 34: {
            String s = input.readStringRequireUtf8();

            deviceName_ = s;
            break;
          }
          case 42: {
            String s = input.readStringRequireUtf8();

            deviceLoc_ = s;
            break;
          }
          case 50: {
            com.intellif.ifai.common.Image.Builder subBuilder = null;
            if (image_ != null) {
              subBuilder = image_.toBuilder();
            }
            image_ = input.readMessage(com.intellif.ifai.common.Image.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(image_);
              image_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return Ifai.internal_static_Ifaipb_CallPadRequest_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return Ifai.internal_static_Ifaipb_CallPadRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            CallPadRequest.class, Builder.class);
  }

  public static final int RECORD_ID_FIELD_NUMBER = 1;
  private com.intellif.ifai.common.CommonInt recordId_;
  /**
   * <pre>
   *记录id
   * </pre>
   *
   * <code>.Ifaipb.CommonInt record_id = 1;</code>
   */
  public boolean hasRecordId() {
    return recordId_ != null;
  }
  /**
   * <pre>
   *记录id
   * </pre>
   *
   * <code>.Ifaipb.CommonInt record_id = 1;</code>
   */
  public com.intellif.ifai.common.CommonInt getRecordId() {
    return recordId_ == null ? com.intellif.ifai.common.CommonInt.getDefaultInstance() : recordId_;
  }
  /**
   * <pre>
   *记录id
   * </pre>
   *
   * <code>.Ifaipb.CommonInt record_id = 1;</code>
   */
  public com.intellif.ifai.common.CommonIntOrBuilder getRecordIdOrBuilder() {
    return getRecordId();
  }

  public static final int CAPTURE_ID_FIELD_NUMBER = 2;
  private volatile Object captureId_;
  /**
   * <pre>
   * P2P对讲所需字段
   * </pre>
   *
   * <code>string capture_id = 2;</code>
   */
  public String getCaptureId() {
    Object ref = captureId_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      captureId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * P2P对讲所需字段
   * </pre>
   *
   * <code>string capture_id = 2;</code>
   */
  public com.google.protobuf.ByteString
      getCaptureIdBytes() {
    Object ref = captureId_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      captureId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DEVICE_ID_FIELD_NUMBER = 3;
  private volatile Object deviceId_;
  /**
   * <pre>
   * 设备ID
   * </pre>
   *
   * <code>string device_id = 3;</code>
   */
  public String getDeviceId() {
    Object ref = deviceId_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      deviceId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 设备ID
   * </pre>
   *
   * <code>string device_id = 3;</code>
   */
  public com.google.protobuf.ByteString
      getDeviceIdBytes() {
    Object ref = deviceId_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      deviceId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DEVICE_NAME_FIELD_NUMBER = 4;
  private volatile Object deviceName_;
  /**
   * <pre>
   *设备名称
   * </pre>
   *
   * <code>string device_name = 4;</code>
   */
  public String getDeviceName() {
    Object ref = deviceName_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      deviceName_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *设备名称
   * </pre>
   *
   * <code>string device_name = 4;</code>
   */
  public com.google.protobuf.ByteString
      getDeviceNameBytes() {
    Object ref = deviceName_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      deviceName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DEVICE_LOC_FIELD_NUMBER = 5;
  private volatile Object deviceLoc_;
  /**
   * <pre>
   *设备位置
   * </pre>
   *
   * <code>string device_loc = 5;</code>
   */
  public String getDeviceLoc() {
    Object ref = deviceLoc_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      deviceLoc_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *设备位置
   * </pre>
   *
   * <code>string device_loc = 5;</code>
   */
  public com.google.protobuf.ByteString
      getDeviceLocBytes() {
    Object ref = deviceLoc_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      deviceLoc_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int IMAGE_FIELD_NUMBER = 6;
  private com.intellif.ifai.common.Image image_;
  /**
   * <pre>
   *抓拍图片
   * </pre>
   *
   * <code>.Ifaipb.Image image = 6;</code>
   */
  public boolean hasImage() {
    return image_ != null;
  }
  /**
   * <pre>
   *抓拍图片
   * </pre>
   *
   * <code>.Ifaipb.Image image = 6;</code>
   */
  public com.intellif.ifai.common.Image getImage() {
    return image_ == null ? com.intellif.ifai.common.Image.getDefaultInstance() : image_;
  }
  /**
   * <pre>
   *抓拍图片
   * </pre>
   *
   * <code>.Ifaipb.Image image = 6;</code>
   */
  public com.intellif.ifai.common.ImageOrBuilder getImageOrBuilder() {
    return getImage();
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (recordId_ != null) {
      output.writeMessage(1, getRecordId());
    }
    if (!getCaptureIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, captureId_);
    }
    if (!getDeviceIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, deviceId_);
    }
    if (!getDeviceNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, deviceName_);
    }
    if (!getDeviceLocBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, deviceLoc_);
    }
    if (image_ != null) {
      output.writeMessage(6, getImage());
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (recordId_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getRecordId());
    }
    if (!getCaptureIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, captureId_);
    }
    if (!getDeviceIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, deviceId_);
    }
    if (!getDeviceNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, deviceName_);
    }
    if (!getDeviceLocBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, deviceLoc_);
    }
    if (image_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, getImage());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof CallPadRequest)) {
      return super.equals(obj);
    }
    CallPadRequest other = (CallPadRequest) obj;

    boolean result = true;
    result = result && (hasRecordId() == other.hasRecordId());
    if (hasRecordId()) {
      result = result && getRecordId()
          .equals(other.getRecordId());
    }
    result = result && getCaptureId()
        .equals(other.getCaptureId());
    result = result && getDeviceId()
        .equals(other.getDeviceId());
    result = result && getDeviceName()
        .equals(other.getDeviceName());
    result = result && getDeviceLoc()
        .equals(other.getDeviceLoc());
    result = result && (hasImage() == other.hasImage());
    if (hasImage()) {
      result = result && getImage()
          .equals(other.getImage());
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasRecordId()) {
      hash = (37 * hash) + RECORD_ID_FIELD_NUMBER;
      hash = (53 * hash) + getRecordId().hashCode();
    }
    hash = (37 * hash) + CAPTURE_ID_FIELD_NUMBER;
    hash = (53 * hash) + getCaptureId().hashCode();
    hash = (37 * hash) + DEVICE_ID_FIELD_NUMBER;
    hash = (53 * hash) + getDeviceId().hashCode();
    hash = (37 * hash) + DEVICE_NAME_FIELD_NUMBER;
    hash = (53 * hash) + getDeviceName().hashCode();
    hash = (37 * hash) + DEVICE_LOC_FIELD_NUMBER;
    hash = (53 * hash) + getDeviceLoc().hashCode();
    if (hasImage()) {
      hash = (37 * hash) + IMAGE_FIELD_NUMBER;
      hash = (53 * hash) + getImage().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static CallPadRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static CallPadRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static CallPadRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static CallPadRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static CallPadRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static CallPadRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static CallPadRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static CallPadRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static CallPadRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static CallPadRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static CallPadRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static CallPadRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(CallPadRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   *平台通知平板接听呼叫请求
   * </pre>
   *
   * Protobuf type {@code Ifaipb.CallPadRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Ifaipb.CallPadRequest)
      CallPadRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Ifai.internal_static_Ifaipb_CallPadRequest_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Ifai.internal_static_Ifaipb_CallPadRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              CallPadRequest.class, Builder.class);
    }

    // Construct using com.intellif.ifai.padVideoIntercom.CallPadRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      if (recordIdBuilder_ == null) {
        recordId_ = null;
      } else {
        recordId_ = null;
        recordIdBuilder_ = null;
      }
      captureId_ = "";

      deviceId_ = "";

      deviceName_ = "";

      deviceLoc_ = "";

      if (imageBuilder_ == null) {
        image_ = null;
      } else {
        image_ = null;
        imageBuilder_ = null;
      }
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return Ifai.internal_static_Ifaipb_CallPadRequest_descriptor;
    }

    @Override
    public CallPadRequest getDefaultInstanceForType() {
      return CallPadRequest.getDefaultInstance();
    }

    @Override
    public CallPadRequest build() {
      CallPadRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public CallPadRequest buildPartial() {
      CallPadRequest result = new CallPadRequest(this);
      if (recordIdBuilder_ == null) {
        result.recordId_ = recordId_;
      } else {
        result.recordId_ = recordIdBuilder_.build();
      }
      result.captureId_ = captureId_;
      result.deviceId_ = deviceId_;
      result.deviceName_ = deviceName_;
      result.deviceLoc_ = deviceLoc_;
      if (imageBuilder_ == null) {
        result.image_ = image_;
      } else {
        result.image_ = imageBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof CallPadRequest) {
        return mergeFrom((CallPadRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(CallPadRequest other) {
      if (other == CallPadRequest.getDefaultInstance()) return this;
      if (other.hasRecordId()) {
        mergeRecordId(other.getRecordId());
      }
      if (!other.getCaptureId().isEmpty()) {
        captureId_ = other.captureId_;
        onChanged();
      }
      if (!other.getDeviceId().isEmpty()) {
        deviceId_ = other.deviceId_;
        onChanged();
      }
      if (!other.getDeviceName().isEmpty()) {
        deviceName_ = other.deviceName_;
        onChanged();
      }
      if (!other.getDeviceLoc().isEmpty()) {
        deviceLoc_ = other.deviceLoc_;
        onChanged();
      }
      if (other.hasImage()) {
        mergeImage(other.getImage());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      CallPadRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (CallPadRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private com.intellif.ifai.common.CommonInt recordId_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.intellif.ifai.common.CommonInt, com.intellif.ifai.common.CommonInt.Builder, com.intellif.ifai.common.CommonIntOrBuilder> recordIdBuilder_;
    /**
     * <pre>
     *记录id
     * </pre>
     *
     * <code>.Ifaipb.CommonInt record_id = 1;</code>
     */
    public boolean hasRecordId() {
      return recordIdBuilder_ != null || recordId_ != null;
    }
    /**
     * <pre>
     *记录id
     * </pre>
     *
     * <code>.Ifaipb.CommonInt record_id = 1;</code>
     */
    public com.intellif.ifai.common.CommonInt getRecordId() {
      if (recordIdBuilder_ == null) {
        return recordId_ == null ? com.intellif.ifai.common.CommonInt.getDefaultInstance() : recordId_;
      } else {
        return recordIdBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     *记录id
     * </pre>
     *
     * <code>.Ifaipb.CommonInt record_id = 1;</code>
     */
    public Builder setRecordId(com.intellif.ifai.common.CommonInt value) {
      if (recordIdBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        recordId_ = value;
        onChanged();
      } else {
        recordIdBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     *记录id
     * </pre>
     *
     * <code>.Ifaipb.CommonInt record_id = 1;</code>
     */
    public Builder setRecordId(
        com.intellif.ifai.common.CommonInt.Builder builderForValue) {
      if (recordIdBuilder_ == null) {
        recordId_ = builderForValue.build();
        onChanged();
      } else {
        recordIdBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     *记录id
     * </pre>
     *
     * <code>.Ifaipb.CommonInt record_id = 1;</code>
     */
    public Builder mergeRecordId(com.intellif.ifai.common.CommonInt value) {
      if (recordIdBuilder_ == null) {
        if (recordId_ != null) {
          recordId_ =
            com.intellif.ifai.common.CommonInt.newBuilder(recordId_).mergeFrom(value).buildPartial();
        } else {
          recordId_ = value;
        }
        onChanged();
      } else {
        recordIdBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     *记录id
     * </pre>
     *
     * <code>.Ifaipb.CommonInt record_id = 1;</code>
     */
    public Builder clearRecordId() {
      if (recordIdBuilder_ == null) {
        recordId_ = null;
        onChanged();
      } else {
        recordId_ = null;
        recordIdBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     *记录id
     * </pre>
     *
     * <code>.Ifaipb.CommonInt record_id = 1;</code>
     */
    public com.intellif.ifai.common.CommonInt.Builder getRecordIdBuilder() {
      
      onChanged();
      return getRecordIdFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     *记录id
     * </pre>
     *
     * <code>.Ifaipb.CommonInt record_id = 1;</code>
     */
    public com.intellif.ifai.common.CommonIntOrBuilder getRecordIdOrBuilder() {
      if (recordIdBuilder_ != null) {
        return recordIdBuilder_.getMessageOrBuilder();
      } else {
        return recordId_ == null ?
            com.intellif.ifai.common.CommonInt.getDefaultInstance() : recordId_;
      }
    }
    /**
     * <pre>
     *记录id
     * </pre>
     *
     * <code>.Ifaipb.CommonInt record_id = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.intellif.ifai.common.CommonInt, com.intellif.ifai.common.CommonInt.Builder, com.intellif.ifai.common.CommonIntOrBuilder> 
        getRecordIdFieldBuilder() {
      if (recordIdBuilder_ == null) {
        recordIdBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.intellif.ifai.common.CommonInt, com.intellif.ifai.common.CommonInt.Builder, com.intellif.ifai.common.CommonIntOrBuilder>(
                getRecordId(),
                getParentForChildren(),
                isClean());
        recordId_ = null;
      }
      return recordIdBuilder_;
    }

    private Object captureId_ = "";
    /**
     * <pre>
     * P2P对讲所需字段
     * </pre>
     *
     * <code>string capture_id = 2;</code>
     */
    public String getCaptureId() {
      Object ref = captureId_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        captureId_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     * P2P对讲所需字段
     * </pre>
     *
     * <code>string capture_id = 2;</code>
     */
    public com.google.protobuf.ByteString
        getCaptureIdBytes() {
      Object ref = captureId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        captureId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * P2P对讲所需字段
     * </pre>
     *
     * <code>string capture_id = 2;</code>
     */
    public Builder setCaptureId(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      captureId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * P2P对讲所需字段
     * </pre>
     *
     * <code>string capture_id = 2;</code>
     */
    public Builder clearCaptureId() {
      
      captureId_ = getDefaultInstance().getCaptureId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * P2P对讲所需字段
     * </pre>
     *
     * <code>string capture_id = 2;</code>
     */
    public Builder setCaptureIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      captureId_ = value;
      onChanged();
      return this;
    }

    private Object deviceId_ = "";
    /**
     * <pre>
     * 设备ID
     * </pre>
     *
     * <code>string device_id = 3;</code>
     */
    public String getDeviceId() {
      Object ref = deviceId_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        deviceId_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     * 设备ID
     * </pre>
     *
     * <code>string device_id = 3;</code>
     */
    public com.google.protobuf.ByteString
        getDeviceIdBytes() {
      Object ref = deviceId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        deviceId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 设备ID
     * </pre>
     *
     * <code>string device_id = 3;</code>
     */
    public Builder setDeviceId(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      deviceId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 设备ID
     * </pre>
     *
     * <code>string device_id = 3;</code>
     */
    public Builder clearDeviceId() {
      
      deviceId_ = getDefaultInstance().getDeviceId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 设备ID
     * </pre>
     *
     * <code>string device_id = 3;</code>
     */
    public Builder setDeviceIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      deviceId_ = value;
      onChanged();
      return this;
    }

    private Object deviceName_ = "";
    /**
     * <pre>
     *设备名称
     * </pre>
     *
     * <code>string device_name = 4;</code>
     */
    public String getDeviceName() {
      Object ref = deviceName_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        deviceName_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     *设备名称
     * </pre>
     *
     * <code>string device_name = 4;</code>
     */
    public com.google.protobuf.ByteString
        getDeviceNameBytes() {
      Object ref = deviceName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        deviceName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *设备名称
     * </pre>
     *
     * <code>string device_name = 4;</code>
     */
    public Builder setDeviceName(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      deviceName_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *设备名称
     * </pre>
     *
     * <code>string device_name = 4;</code>
     */
    public Builder clearDeviceName() {
      
      deviceName_ = getDefaultInstance().getDeviceName();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *设备名称
     * </pre>
     *
     * <code>string device_name = 4;</code>
     */
    public Builder setDeviceNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      deviceName_ = value;
      onChanged();
      return this;
    }

    private Object deviceLoc_ = "";
    /**
     * <pre>
     *设备位置
     * </pre>
     *
     * <code>string device_loc = 5;</code>
     */
    public String getDeviceLoc() {
      Object ref = deviceLoc_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        deviceLoc_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     *设备位置
     * </pre>
     *
     * <code>string device_loc = 5;</code>
     */
    public com.google.protobuf.ByteString
        getDeviceLocBytes() {
      Object ref = deviceLoc_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        deviceLoc_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *设备位置
     * </pre>
     *
     * <code>string device_loc = 5;</code>
     */
    public Builder setDeviceLoc(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      deviceLoc_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *设备位置
     * </pre>
     *
     * <code>string device_loc = 5;</code>
     */
    public Builder clearDeviceLoc() {
      
      deviceLoc_ = getDefaultInstance().getDeviceLoc();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *设备位置
     * </pre>
     *
     * <code>string device_loc = 5;</code>
     */
    public Builder setDeviceLocBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      deviceLoc_ = value;
      onChanged();
      return this;
    }

    private com.intellif.ifai.common.Image image_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.intellif.ifai.common.Image, com.intellif.ifai.common.Image.Builder, com.intellif.ifai.common.ImageOrBuilder> imageBuilder_;
    /**
     * <pre>
     *抓拍图片
     * </pre>
     *
     * <code>.Ifaipb.Image image = 6;</code>
     */
    public boolean hasImage() {
      return imageBuilder_ != null || image_ != null;
    }
    /**
     * <pre>
     *抓拍图片
     * </pre>
     *
     * <code>.Ifaipb.Image image = 6;</code>
     */
    public com.intellif.ifai.common.Image getImage() {
      if (imageBuilder_ == null) {
        return image_ == null ? com.intellif.ifai.common.Image.getDefaultInstance() : image_;
      } else {
        return imageBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     *抓拍图片
     * </pre>
     *
     * <code>.Ifaipb.Image image = 6;</code>
     */
    public Builder setImage(com.intellif.ifai.common.Image value) {
      if (imageBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        image_ = value;
        onChanged();
      } else {
        imageBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     *抓拍图片
     * </pre>
     *
     * <code>.Ifaipb.Image image = 6;</code>
     */
    public Builder setImage(
        com.intellif.ifai.common.Image.Builder builderForValue) {
      if (imageBuilder_ == null) {
        image_ = builderForValue.build();
        onChanged();
      } else {
        imageBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     *抓拍图片
     * </pre>
     *
     * <code>.Ifaipb.Image image = 6;</code>
     */
    public Builder mergeImage(com.intellif.ifai.common.Image value) {
      if (imageBuilder_ == null) {
        if (image_ != null) {
          image_ =
            com.intellif.ifai.common.Image.newBuilder(image_).mergeFrom(value).buildPartial();
        } else {
          image_ = value;
        }
        onChanged();
      } else {
        imageBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     *抓拍图片
     * </pre>
     *
     * <code>.Ifaipb.Image image = 6;</code>
     */
    public Builder clearImage() {
      if (imageBuilder_ == null) {
        image_ = null;
        onChanged();
      } else {
        image_ = null;
        imageBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     *抓拍图片
     * </pre>
     *
     * <code>.Ifaipb.Image image = 6;</code>
     */
    public com.intellif.ifai.common.Image.Builder getImageBuilder() {
      
      onChanged();
      return getImageFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     *抓拍图片
     * </pre>
     *
     * <code>.Ifaipb.Image image = 6;</code>
     */
    public com.intellif.ifai.common.ImageOrBuilder getImageOrBuilder() {
      if (imageBuilder_ != null) {
        return imageBuilder_.getMessageOrBuilder();
      } else {
        return image_ == null ?
            com.intellif.ifai.common.Image.getDefaultInstance() : image_;
      }
    }
    /**
     * <pre>
     *抓拍图片
     * </pre>
     *
     * <code>.Ifaipb.Image image = 6;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.intellif.ifai.common.Image, com.intellif.ifai.common.Image.Builder, com.intellif.ifai.common.ImageOrBuilder> 
        getImageFieldBuilder() {
      if (imageBuilder_ == null) {
        imageBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.intellif.ifai.common.Image, com.intellif.ifai.common.Image.Builder, com.intellif.ifai.common.ImageOrBuilder>(
                getImage(),
                getParentForChildren(),
                isClean());
        image_ = null;
      }
      return imageBuilder_;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:Ifaipb.CallPadRequest)
  }

  // @@protoc_insertion_point(class_scope:Ifaipb.CallPadRequest)
  private static final CallPadRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new CallPadRequest();
  }

  public static CallPadRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CallPadRequest>
      PARSER = new com.google.protobuf.AbstractParser<CallPadRequest>() {
    @Override
    public CallPadRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new CallPadRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<CallPadRequest> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<CallPadRequest> getParserForType() {
    return PARSER;
  }

  @Override
  public CallPadRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

