// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: IfCommonType.proto

package com.intellif.ifai.common;

public interface TimePeriodOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Ifaipb.TimePeriod)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.Ifaipb.Time begin = 1;</code>
   */
  boolean hasBegin();
  /**
   * <code>.Ifaipb.Time begin = 1;</code>
   */
  com.intellif.ifai.common.Time getBegin();
  /**
   * <code>.Ifaipb.Time begin = 1;</code>
   */
  com.intellif.ifai.common.TimeOrBuilder getBeginOrBuilder();

  /**
   * <code>.Ifaipb.Time end = 2;</code>
   */
  boolean hasEnd();
  /**
   * <code>.Ifaipb.Time end = 2;</code>
   */
  com.intellif.ifai.common.Time getEnd();
  /**
   * <code>.Ifaipb.Time end = 2;</code>
   */
  com.intellif.ifai.common.TimeOrBuilder getEndOrBuilder();
}
