// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: IfCommonType.proto

package com.intellif.ifai.common;

/**
 * Protobuf type {@code Ifaipb.TimePeriod}
 */
public  final class TimePeriod extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:Ifaipb.TimePeriod)
    TimePeriodOrBuilder {
private static final long serialVersionUID = 0L;
  // Use TimePeriod.newBuilder() to construct.
  private TimePeriod(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private TimePeriod() {
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private TimePeriod(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            com.intellif.ifai.common.Time.Builder subBuilder = null;
            if (begin_ != null) {
              subBuilder = begin_.toBuilder();
            }
            begin_ = input.readMessage(com.intellif.ifai.common.Time.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(begin_);
              begin_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            com.intellif.ifai.common.Time.Builder subBuilder = null;
            if (end_ != null) {
              subBuilder = end_.toBuilder();
            }
            end_ = input.readMessage(com.intellif.ifai.common.Time.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(end_);
              end_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.intellif.ifai.common.Ifai.internal_static_Ifaipb_TimePeriod_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.intellif.ifai.common.Ifai.internal_static_Ifaipb_TimePeriod_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.intellif.ifai.common.TimePeriod.class, com.intellif.ifai.common.TimePeriod.Builder.class);
  }

  public static final int BEGIN_FIELD_NUMBER = 1;
  private com.intellif.ifai.common.Time begin_;
  /**
   * <code>.Ifaipb.Time begin = 1;</code>
   */
  public boolean hasBegin() {
    return begin_ != null;
  }
  /**
   * <code>.Ifaipb.Time begin = 1;</code>
   */
  public com.intellif.ifai.common.Time getBegin() {
    return begin_ == null ? com.intellif.ifai.common.Time.getDefaultInstance() : begin_;
  }
  /**
   * <code>.Ifaipb.Time begin = 1;</code>
   */
  public com.intellif.ifai.common.TimeOrBuilder getBeginOrBuilder() {
    return getBegin();
  }

  public static final int END_FIELD_NUMBER = 2;
  private com.intellif.ifai.common.Time end_;
  /**
   * <code>.Ifaipb.Time end = 2;</code>
   */
  public boolean hasEnd() {
    return end_ != null;
  }
  /**
   * <code>.Ifaipb.Time end = 2;</code>
   */
  public com.intellif.ifai.common.Time getEnd() {
    return end_ == null ? com.intellif.ifai.common.Time.getDefaultInstance() : end_;
  }
  /**
   * <code>.Ifaipb.Time end = 2;</code>
   */
  public com.intellif.ifai.common.TimeOrBuilder getEndOrBuilder() {
    return getEnd();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (begin_ != null) {
      output.writeMessage(1, getBegin());
    }
    if (end_ != null) {
      output.writeMessage(2, getEnd());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (begin_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getBegin());
    }
    if (end_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getEnd());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.intellif.ifai.common.TimePeriod)) {
      return super.equals(obj);
    }
    com.intellif.ifai.common.TimePeriod other = (com.intellif.ifai.common.TimePeriod) obj;

    boolean result = true;
    result = result && (hasBegin() == other.hasBegin());
    if (hasBegin()) {
      result = result && getBegin()
          .equals(other.getBegin());
    }
    result = result && (hasEnd() == other.hasEnd());
    if (hasEnd()) {
      result = result && getEnd()
          .equals(other.getEnd());
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasBegin()) {
      hash = (37 * hash) + BEGIN_FIELD_NUMBER;
      hash = (53 * hash) + getBegin().hashCode();
    }
    if (hasEnd()) {
      hash = (37 * hash) + END_FIELD_NUMBER;
      hash = (53 * hash) + getEnd().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.intellif.ifai.common.TimePeriod parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.intellif.ifai.common.TimePeriod parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.intellif.ifai.common.TimePeriod parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.intellif.ifai.common.TimePeriod parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.intellif.ifai.common.TimePeriod parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.intellif.ifai.common.TimePeriod parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.intellif.ifai.common.TimePeriod parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.intellif.ifai.common.TimePeriod parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.intellif.ifai.common.TimePeriod parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.intellif.ifai.common.TimePeriod parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.intellif.ifai.common.TimePeriod parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.intellif.ifai.common.TimePeriod parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.intellif.ifai.common.TimePeriod prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code Ifaipb.TimePeriod}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Ifaipb.TimePeriod)
      com.intellif.ifai.common.TimePeriodOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.intellif.ifai.common.Ifai.internal_static_Ifaipb_TimePeriod_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.intellif.ifai.common.Ifai.internal_static_Ifaipb_TimePeriod_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.intellif.ifai.common.TimePeriod.class, com.intellif.ifai.common.TimePeriod.Builder.class);
    }

    // Construct using com.intellif.ifai.common.TimePeriod.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (beginBuilder_ == null) {
        begin_ = null;
      } else {
        begin_ = null;
        beginBuilder_ = null;
      }
      if (endBuilder_ == null) {
        end_ = null;
      } else {
        end_ = null;
        endBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.intellif.ifai.common.Ifai.internal_static_Ifaipb_TimePeriod_descriptor;
    }

    @java.lang.Override
    public com.intellif.ifai.common.TimePeriod getDefaultInstanceForType() {
      return com.intellif.ifai.common.TimePeriod.getDefaultInstance();
    }

    @java.lang.Override
    public com.intellif.ifai.common.TimePeriod build() {
      com.intellif.ifai.common.TimePeriod result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.intellif.ifai.common.TimePeriod buildPartial() {
      com.intellif.ifai.common.TimePeriod result = new com.intellif.ifai.common.TimePeriod(this);
      if (beginBuilder_ == null) {
        result.begin_ = begin_;
      } else {
        result.begin_ = beginBuilder_.build();
      }
      if (endBuilder_ == null) {
        result.end_ = end_;
      } else {
        result.end_ = endBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.intellif.ifai.common.TimePeriod) {
        return mergeFrom((com.intellif.ifai.common.TimePeriod)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.intellif.ifai.common.TimePeriod other) {
      if (other == com.intellif.ifai.common.TimePeriod.getDefaultInstance()) return this;
      if (other.hasBegin()) {
        mergeBegin(other.getBegin());
      }
      if (other.hasEnd()) {
        mergeEnd(other.getEnd());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.intellif.ifai.common.TimePeriod parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.intellif.ifai.common.TimePeriod) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private com.intellif.ifai.common.Time begin_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.intellif.ifai.common.Time, com.intellif.ifai.common.Time.Builder, com.intellif.ifai.common.TimeOrBuilder> beginBuilder_;
    /**
     * <code>.Ifaipb.Time begin = 1;</code>
     */
    public boolean hasBegin() {
      return beginBuilder_ != null || begin_ != null;
    }
    /**
     * <code>.Ifaipb.Time begin = 1;</code>
     */
    public com.intellif.ifai.common.Time getBegin() {
      if (beginBuilder_ == null) {
        return begin_ == null ? com.intellif.ifai.common.Time.getDefaultInstance() : begin_;
      } else {
        return beginBuilder_.getMessage();
      }
    }
    /**
     * <code>.Ifaipb.Time begin = 1;</code>
     */
    public Builder setBegin(com.intellif.ifai.common.Time value) {
      if (beginBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        begin_ = value;
        onChanged();
      } else {
        beginBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.Ifaipb.Time begin = 1;</code>
     */
    public Builder setBegin(
        com.intellif.ifai.common.Time.Builder builderForValue) {
      if (beginBuilder_ == null) {
        begin_ = builderForValue.build();
        onChanged();
      } else {
        beginBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.Ifaipb.Time begin = 1;</code>
     */
    public Builder mergeBegin(com.intellif.ifai.common.Time value) {
      if (beginBuilder_ == null) {
        if (begin_ != null) {
          begin_ =
            com.intellif.ifai.common.Time.newBuilder(begin_).mergeFrom(value).buildPartial();
        } else {
          begin_ = value;
        }
        onChanged();
      } else {
        beginBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.Ifaipb.Time begin = 1;</code>
     */
    public Builder clearBegin() {
      if (beginBuilder_ == null) {
        begin_ = null;
        onChanged();
      } else {
        begin_ = null;
        beginBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.Ifaipb.Time begin = 1;</code>
     */
    public com.intellif.ifai.common.Time.Builder getBeginBuilder() {
      
      onChanged();
      return getBeginFieldBuilder().getBuilder();
    }
    /**
     * <code>.Ifaipb.Time begin = 1;</code>
     */
    public com.intellif.ifai.common.TimeOrBuilder getBeginOrBuilder() {
      if (beginBuilder_ != null) {
        return beginBuilder_.getMessageOrBuilder();
      } else {
        return begin_ == null ?
            com.intellif.ifai.common.Time.getDefaultInstance() : begin_;
      }
    }
    /**
     * <code>.Ifaipb.Time begin = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.intellif.ifai.common.Time, com.intellif.ifai.common.Time.Builder, com.intellif.ifai.common.TimeOrBuilder> 
        getBeginFieldBuilder() {
      if (beginBuilder_ == null) {
        beginBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.intellif.ifai.common.Time, com.intellif.ifai.common.Time.Builder, com.intellif.ifai.common.TimeOrBuilder>(
                getBegin(),
                getParentForChildren(),
                isClean());
        begin_ = null;
      }
      return beginBuilder_;
    }

    private com.intellif.ifai.common.Time end_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.intellif.ifai.common.Time, com.intellif.ifai.common.Time.Builder, com.intellif.ifai.common.TimeOrBuilder> endBuilder_;
    /**
     * <code>.Ifaipb.Time end = 2;</code>
     */
    public boolean hasEnd() {
      return endBuilder_ != null || end_ != null;
    }
    /**
     * <code>.Ifaipb.Time end = 2;</code>
     */
    public com.intellif.ifai.common.Time getEnd() {
      if (endBuilder_ == null) {
        return end_ == null ? com.intellif.ifai.common.Time.getDefaultInstance() : end_;
      } else {
        return endBuilder_.getMessage();
      }
    }
    /**
     * <code>.Ifaipb.Time end = 2;</code>
     */
    public Builder setEnd(com.intellif.ifai.common.Time value) {
      if (endBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        end_ = value;
        onChanged();
      } else {
        endBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.Ifaipb.Time end = 2;</code>
     */
    public Builder setEnd(
        com.intellif.ifai.common.Time.Builder builderForValue) {
      if (endBuilder_ == null) {
        end_ = builderForValue.build();
        onChanged();
      } else {
        endBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.Ifaipb.Time end = 2;</code>
     */
    public Builder mergeEnd(com.intellif.ifai.common.Time value) {
      if (endBuilder_ == null) {
        if (end_ != null) {
          end_ =
            com.intellif.ifai.common.Time.newBuilder(end_).mergeFrom(value).buildPartial();
        } else {
          end_ = value;
        }
        onChanged();
      } else {
        endBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.Ifaipb.Time end = 2;</code>
     */
    public Builder clearEnd() {
      if (endBuilder_ == null) {
        end_ = null;
        onChanged();
      } else {
        end_ = null;
        endBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.Ifaipb.Time end = 2;</code>
     */
    public com.intellif.ifai.common.Time.Builder getEndBuilder() {
      
      onChanged();
      return getEndFieldBuilder().getBuilder();
    }
    /**
     * <code>.Ifaipb.Time end = 2;</code>
     */
    public com.intellif.ifai.common.TimeOrBuilder getEndOrBuilder() {
      if (endBuilder_ != null) {
        return endBuilder_.getMessageOrBuilder();
      } else {
        return end_ == null ?
            com.intellif.ifai.common.Time.getDefaultInstance() : end_;
      }
    }
    /**
     * <code>.Ifaipb.Time end = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.intellif.ifai.common.Time, com.intellif.ifai.common.Time.Builder, com.intellif.ifai.common.TimeOrBuilder> 
        getEndFieldBuilder() {
      if (endBuilder_ == null) {
        endBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.intellif.ifai.common.Time, com.intellif.ifai.common.Time.Builder, com.intellif.ifai.common.TimeOrBuilder>(
                getEnd(),
                getParentForChildren(),
                isClean());
        end_ = null;
      }
      return endBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:Ifaipb.TimePeriod)
  }

  // @@protoc_insertion_point(class_scope:Ifaipb.TimePeriod)
  private static final com.intellif.ifai.common.TimePeriod DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.intellif.ifai.common.TimePeriod();
  }

  public static com.intellif.ifai.common.TimePeriod getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<TimePeriod>
      PARSER = new com.google.protobuf.AbstractParser<TimePeriod>() {
    @java.lang.Override
    public TimePeriod parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new TimePeriod(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<TimePeriod> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<TimePeriod> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.intellif.ifai.common.TimePeriod getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

