// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: IfCommonType.proto

package com.intellif.ifai.common;

/**
 * Protobuf type {@code Ifaipb.WeekdayTimePeriod}
 */
public  final class WeekdayTimePeriod extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:Ifaipb.WeekdayTimePeriod)
    WeekdayTimePeriodOrBuilder {
private static final long serialVersionUID = 0L;
  // Use WeekdayTimePeriod.newBuilder() to construct.
  private WeekdayTimePeriod(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private WeekdayTimePeriod() {
    day_ = 0;
    period_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private WeekdayTimePeriod(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {
            int rawValue = input.readEnum();

            day_ = rawValue;
            break;
          }
          case 18: {
            if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
              period_ = new java.util.ArrayList<com.intellif.ifai.common.TimePeriod>();
              mutable_bitField0_ |= 0x00000002;
            }
            period_.add(
                input.readMessage(com.intellif.ifai.common.TimePeriod.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
        period_ = java.util.Collections.unmodifiableList(period_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.intellif.ifai.common.Ifai.internal_static_Ifaipb_WeekdayTimePeriod_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.intellif.ifai.common.Ifai.internal_static_Ifaipb_WeekdayTimePeriod_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.intellif.ifai.common.WeekdayTimePeriod.class, com.intellif.ifai.common.WeekdayTimePeriod.Builder.class);
  }

  private int bitField0_;
  public static final int DAY_FIELD_NUMBER = 1;
  private int day_;
  /**
   * <code>.Ifaipb.Weekday day = 1;</code>
   */
  public int getDayValue() {
    return day_;
  }
  /**
   * <code>.Ifaipb.Weekday day = 1;</code>
   */
  public com.intellif.ifai.common.Weekday getDay() {
    @SuppressWarnings("deprecation")
    com.intellif.ifai.common.Weekday result = com.intellif.ifai.common.Weekday.valueOf(day_);
    return result == null ? com.intellif.ifai.common.Weekday.UNRECOGNIZED : result;
  }

  public static final int PERIOD_FIELD_NUMBER = 2;
  private java.util.List<com.intellif.ifai.common.TimePeriod> period_;
  /**
   * <code>repeated .Ifaipb.TimePeriod period = 2;</code>
   */
  public java.util.List<com.intellif.ifai.common.TimePeriod> getPeriodList() {
    return period_;
  }
  /**
   * <code>repeated .Ifaipb.TimePeriod period = 2;</code>
   */
  public java.util.List<? extends com.intellif.ifai.common.TimePeriodOrBuilder> 
      getPeriodOrBuilderList() {
    return period_;
  }
  /**
   * <code>repeated .Ifaipb.TimePeriod period = 2;</code>
   */
  public int getPeriodCount() {
    return period_.size();
  }
  /**
   * <code>repeated .Ifaipb.TimePeriod period = 2;</code>
   */
  public com.intellif.ifai.common.TimePeriod getPeriod(int index) {
    return period_.get(index);
  }
  /**
   * <code>repeated .Ifaipb.TimePeriod period = 2;</code>
   */
  public com.intellif.ifai.common.TimePeriodOrBuilder getPeriodOrBuilder(
      int index) {
    return period_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (day_ != com.intellif.ifai.common.Weekday.Weekday_Sunday.getNumber()) {
      output.writeEnum(1, day_);
    }
    for (int i = 0; i < period_.size(); i++) {
      output.writeMessage(2, period_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (day_ != com.intellif.ifai.common.Weekday.Weekday_Sunday.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, day_);
    }
    for (int i = 0; i < period_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, period_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.intellif.ifai.common.WeekdayTimePeriod)) {
      return super.equals(obj);
    }
    com.intellif.ifai.common.WeekdayTimePeriod other = (com.intellif.ifai.common.WeekdayTimePeriod) obj;

    boolean result = true;
    result = result && day_ == other.day_;
    result = result && getPeriodList()
        .equals(other.getPeriodList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + DAY_FIELD_NUMBER;
    hash = (53 * hash) + day_;
    if (getPeriodCount() > 0) {
      hash = (37 * hash) + PERIOD_FIELD_NUMBER;
      hash = (53 * hash) + getPeriodList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.intellif.ifai.common.WeekdayTimePeriod parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.intellif.ifai.common.WeekdayTimePeriod parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.intellif.ifai.common.WeekdayTimePeriod parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.intellif.ifai.common.WeekdayTimePeriod parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.intellif.ifai.common.WeekdayTimePeriod parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.intellif.ifai.common.WeekdayTimePeriod parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.intellif.ifai.common.WeekdayTimePeriod parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.intellif.ifai.common.WeekdayTimePeriod parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.intellif.ifai.common.WeekdayTimePeriod parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.intellif.ifai.common.WeekdayTimePeriod parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.intellif.ifai.common.WeekdayTimePeriod parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.intellif.ifai.common.WeekdayTimePeriod parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.intellif.ifai.common.WeekdayTimePeriod prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code Ifaipb.WeekdayTimePeriod}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Ifaipb.WeekdayTimePeriod)
      com.intellif.ifai.common.WeekdayTimePeriodOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.intellif.ifai.common.Ifai.internal_static_Ifaipb_WeekdayTimePeriod_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.intellif.ifai.common.Ifai.internal_static_Ifaipb_WeekdayTimePeriod_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.intellif.ifai.common.WeekdayTimePeriod.class, com.intellif.ifai.common.WeekdayTimePeriod.Builder.class);
    }

    // Construct using com.intellif.ifai.common.WeekdayTimePeriod.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getPeriodFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      day_ = 0;

      if (periodBuilder_ == null) {
        period_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
      } else {
        periodBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.intellif.ifai.common.Ifai.internal_static_Ifaipb_WeekdayTimePeriod_descriptor;
    }

    @java.lang.Override
    public com.intellif.ifai.common.WeekdayTimePeriod getDefaultInstanceForType() {
      return com.intellif.ifai.common.WeekdayTimePeriod.getDefaultInstance();
    }

    @java.lang.Override
    public com.intellif.ifai.common.WeekdayTimePeriod build() {
      com.intellif.ifai.common.WeekdayTimePeriod result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.intellif.ifai.common.WeekdayTimePeriod buildPartial() {
      com.intellif.ifai.common.WeekdayTimePeriod result = new com.intellif.ifai.common.WeekdayTimePeriod(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.day_ = day_;
      if (periodBuilder_ == null) {
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          period_ = java.util.Collections.unmodifiableList(period_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.period_ = period_;
      } else {
        result.period_ = periodBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.intellif.ifai.common.WeekdayTimePeriod) {
        return mergeFrom((com.intellif.ifai.common.WeekdayTimePeriod)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.intellif.ifai.common.WeekdayTimePeriod other) {
      if (other == com.intellif.ifai.common.WeekdayTimePeriod.getDefaultInstance()) return this;
      if (other.day_ != 0) {
        setDayValue(other.getDayValue());
      }
      if (periodBuilder_ == null) {
        if (!other.period_.isEmpty()) {
          if (period_.isEmpty()) {
            period_ = other.period_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensurePeriodIsMutable();
            period_.addAll(other.period_);
          }
          onChanged();
        }
      } else {
        if (!other.period_.isEmpty()) {
          if (periodBuilder_.isEmpty()) {
            periodBuilder_.dispose();
            periodBuilder_ = null;
            period_ = other.period_;
            bitField0_ = (bitField0_ & ~0x00000002);
            periodBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getPeriodFieldBuilder() : null;
          } else {
            periodBuilder_.addAllMessages(other.period_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.intellif.ifai.common.WeekdayTimePeriod parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.intellif.ifai.common.WeekdayTimePeriod) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private int day_ = 0;
    /**
     * <code>.Ifaipb.Weekday day = 1;</code>
     */
    public int getDayValue() {
      return day_;
    }
    /**
     * <code>.Ifaipb.Weekday day = 1;</code>
     */
    public Builder setDayValue(int value) {
      day_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.Ifaipb.Weekday day = 1;</code>
     */
    public com.intellif.ifai.common.Weekday getDay() {
      @SuppressWarnings("deprecation")
      com.intellif.ifai.common.Weekday result = com.intellif.ifai.common.Weekday.valueOf(day_);
      return result == null ? com.intellif.ifai.common.Weekday.UNRECOGNIZED : result;
    }
    /**
     * <code>.Ifaipb.Weekday day = 1;</code>
     */
    public Builder setDay(com.intellif.ifai.common.Weekday value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      day_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.Ifaipb.Weekday day = 1;</code>
     */
    public Builder clearDay() {
      
      day_ = 0;
      onChanged();
      return this;
    }

    private java.util.List<com.intellif.ifai.common.TimePeriod> period_ =
      java.util.Collections.emptyList();
    private void ensurePeriodIsMutable() {
      if (!((bitField0_ & 0x00000002) == 0x00000002)) {
        period_ = new java.util.ArrayList<com.intellif.ifai.common.TimePeriod>(period_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.intellif.ifai.common.TimePeriod, com.intellif.ifai.common.TimePeriod.Builder, com.intellif.ifai.common.TimePeriodOrBuilder> periodBuilder_;

    /**
     * <code>repeated .Ifaipb.TimePeriod period = 2;</code>
     */
    public java.util.List<com.intellif.ifai.common.TimePeriod> getPeriodList() {
      if (periodBuilder_ == null) {
        return java.util.Collections.unmodifiableList(period_);
      } else {
        return periodBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .Ifaipb.TimePeriod period = 2;</code>
     */
    public int getPeriodCount() {
      if (periodBuilder_ == null) {
        return period_.size();
      } else {
        return periodBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .Ifaipb.TimePeriod period = 2;</code>
     */
    public com.intellif.ifai.common.TimePeriod getPeriod(int index) {
      if (periodBuilder_ == null) {
        return period_.get(index);
      } else {
        return periodBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .Ifaipb.TimePeriod period = 2;</code>
     */
    public Builder setPeriod(
        int index, com.intellif.ifai.common.TimePeriod value) {
      if (periodBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePeriodIsMutable();
        period_.set(index, value);
        onChanged();
      } else {
        periodBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Ifaipb.TimePeriod period = 2;</code>
     */
    public Builder setPeriod(
        int index, com.intellif.ifai.common.TimePeriod.Builder builderForValue) {
      if (periodBuilder_ == null) {
        ensurePeriodIsMutable();
        period_.set(index, builderForValue.build());
        onChanged();
      } else {
        periodBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Ifaipb.TimePeriod period = 2;</code>
     */
    public Builder addPeriod(com.intellif.ifai.common.TimePeriod value) {
      if (periodBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePeriodIsMutable();
        period_.add(value);
        onChanged();
      } else {
        periodBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .Ifaipb.TimePeriod period = 2;</code>
     */
    public Builder addPeriod(
        int index, com.intellif.ifai.common.TimePeriod value) {
      if (periodBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePeriodIsMutable();
        period_.add(index, value);
        onChanged();
      } else {
        periodBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Ifaipb.TimePeriod period = 2;</code>
     */
    public Builder addPeriod(
        com.intellif.ifai.common.TimePeriod.Builder builderForValue) {
      if (periodBuilder_ == null) {
        ensurePeriodIsMutable();
        period_.add(builderForValue.build());
        onChanged();
      } else {
        periodBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Ifaipb.TimePeriod period = 2;</code>
     */
    public Builder addPeriod(
        int index, com.intellif.ifai.common.TimePeriod.Builder builderForValue) {
      if (periodBuilder_ == null) {
        ensurePeriodIsMutable();
        period_.add(index, builderForValue.build());
        onChanged();
      } else {
        periodBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Ifaipb.TimePeriod period = 2;</code>
     */
    public Builder addAllPeriod(
        java.lang.Iterable<? extends com.intellif.ifai.common.TimePeriod> values) {
      if (periodBuilder_ == null) {
        ensurePeriodIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, period_);
        onChanged();
      } else {
        periodBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .Ifaipb.TimePeriod period = 2;</code>
     */
    public Builder clearPeriod() {
      if (periodBuilder_ == null) {
        period_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        periodBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .Ifaipb.TimePeriod period = 2;</code>
     */
    public Builder removePeriod(int index) {
      if (periodBuilder_ == null) {
        ensurePeriodIsMutable();
        period_.remove(index);
        onChanged();
      } else {
        periodBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .Ifaipb.TimePeriod period = 2;</code>
     */
    public com.intellif.ifai.common.TimePeriod.Builder getPeriodBuilder(
        int index) {
      return getPeriodFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .Ifaipb.TimePeriod period = 2;</code>
     */
    public com.intellif.ifai.common.TimePeriodOrBuilder getPeriodOrBuilder(
        int index) {
      if (periodBuilder_ == null) {
        return period_.get(index);  } else {
        return periodBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .Ifaipb.TimePeriod period = 2;</code>
     */
    public java.util.List<? extends com.intellif.ifai.common.TimePeriodOrBuilder> 
         getPeriodOrBuilderList() {
      if (periodBuilder_ != null) {
        return periodBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(period_);
      }
    }
    /**
     * <code>repeated .Ifaipb.TimePeriod period = 2;</code>
     */
    public com.intellif.ifai.common.TimePeriod.Builder addPeriodBuilder() {
      return getPeriodFieldBuilder().addBuilder(
          com.intellif.ifai.common.TimePeriod.getDefaultInstance());
    }
    /**
     * <code>repeated .Ifaipb.TimePeriod period = 2;</code>
     */
    public com.intellif.ifai.common.TimePeriod.Builder addPeriodBuilder(
        int index) {
      return getPeriodFieldBuilder().addBuilder(
          index, com.intellif.ifai.common.TimePeriod.getDefaultInstance());
    }
    /**
     * <code>repeated .Ifaipb.TimePeriod period = 2;</code>
     */
    public java.util.List<com.intellif.ifai.common.TimePeriod.Builder> 
         getPeriodBuilderList() {
      return getPeriodFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.intellif.ifai.common.TimePeriod, com.intellif.ifai.common.TimePeriod.Builder, com.intellif.ifai.common.TimePeriodOrBuilder> 
        getPeriodFieldBuilder() {
      if (periodBuilder_ == null) {
        periodBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.intellif.ifai.common.TimePeriod, com.intellif.ifai.common.TimePeriod.Builder, com.intellif.ifai.common.TimePeriodOrBuilder>(
                period_,
                ((bitField0_ & 0x00000002) == 0x00000002),
                getParentForChildren(),
                isClean());
        period_ = null;
      }
      return periodBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:Ifaipb.WeekdayTimePeriod)
  }

  // @@protoc_insertion_point(class_scope:Ifaipb.WeekdayTimePeriod)
  private static final com.intellif.ifai.common.WeekdayTimePeriod DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.intellif.ifai.common.WeekdayTimePeriod();
  }

  public static com.intellif.ifai.common.WeekdayTimePeriod getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<WeekdayTimePeriod>
      PARSER = new com.google.protobuf.AbstractParser<WeekdayTimePeriod>() {
    @java.lang.Override
    public WeekdayTimePeriod parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new WeekdayTimePeriod(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<WeekdayTimePeriod> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<WeekdayTimePeriod> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.intellif.ifai.common.WeekdayTimePeriod getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

