// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: IfVideoIntercom.proto

package com.intellif.ifai.videoIntercom;

public interface OneClickCallHangUpRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Ifaipb.OneClickCallHangUpRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *当前呼叫设备(门口机)的设备id
   * </pre>
   *
   * <code>string deviceId = 1;</code>
   */
  String getDeviceId();
  /**
   * <pre>
   *当前呼叫设备(门口机)的设备id
   * </pre>
   *
   * <code>string deviceId = 1;</code>
   */
  com.google.protobuf.ByteString
      getDeviceIdBytes();

  /**
   * <pre>
   *记录id
   * </pre>
   *
   * <code>.Ifaipb.CommonInt record_id = 2;</code>
   */
  boolean hasRecordId();
  /**
   * <pre>
   *记录id
   * </pre>
   *
   * <code>.Ifaipb.CommonInt record_id = 2;</code>
   */
  com.intellif.ifai.common.CommonInt getRecordId();
  /**
   * <pre>
   *记录id
   * </pre>
   *
   * <code>.Ifaipb.CommonInt record_id = 2;</code>
   */
  com.intellif.ifai.common.CommonIntOrBuilder getRecordIdOrBuilder();

  /**
   * <pre>
   *抓拍图片
   * </pre>
   *
   * <code>.Ifaipb.Image image = 3;</code>
   */
  boolean hasImage();
  /**
   * <pre>
   *抓拍图片
   * </pre>
   *
   * <code>.Ifaipb.Image image = 3;</code>
   */
  com.intellif.ifai.common.Image getImage();
  /**
   * <pre>
   *抓拍图片
   * </pre>
   *
   * <code>.Ifaipb.Image image = 3;</code>
   */
  com.intellif.ifai.common.ImageOrBuilder getImageOrBuilder();
}
