// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: IfEvent.proto

package com.intellif.ifai.event;

/**
 * Protobuf type {@code Ifaipb.DirectEvents}
 */
public  final class DirectEvents extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:Ifaipb.DirectEvents)
    DirectEventsOrBuilder {
private static final long serialVersionUID = 0L;
  // Use DirectEvents.newBuilder() to construct.
  private DirectEvents(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private DirectEvents() {
    preTrackId_ = 0;
    ruleId_ = 0;
    direct_ = 0;
    trackId_ = 0;
    timestamp_ = 0L;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private DirectEvents(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            preTrackId_ = input.readInt32();
            break;
          }
          case 16: {

            ruleId_ = input.readInt32();
            break;
          }
          case 24: {
            int rawValue = input.readEnum();

            direct_ = rawValue;
            break;
          }
          case 32: {

            trackId_ = input.readInt32();
            break;
          }
          case 40: {

            timestamp_ = input.readInt64();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.intellif.ifai.event.Ifai.internal_static_Ifaipb_DirectEvents_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.intellif.ifai.event.Ifai.internal_static_Ifaipb_DirectEvents_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.intellif.ifai.event.DirectEvents.class, com.intellif.ifai.event.DirectEvents.Builder.class);
  }

  public static final int PRE_TRACK_ID_FIELD_NUMBER = 1;
  private int preTrackId_;
  /**
   * <pre>
   *旧trackid
   * </pre>
   *
   * <code>int32 pre_track_id = 1;</code>
   */
  public int getPreTrackId() {
    return preTrackId_;
  }

  public static final int RULE_ID_FIELD_NUMBER = 2;
  private int ruleId_;
  /**
   * <pre>
   *规则id
   * </pre>
   *
   * <code>int32 rule_id = 2;</code>
   */
  public int getRuleId() {
    return ruleId_;
  }

  public static final int DIRECT_FIELD_NUMBER = 3;
  private int direct_;
  /**
   * <pre>
   * 方向
   * </pre>
   *
   * <code>.Ifaipb.DirectEnum direct = 3;</code>
   */
  public int getDirectValue() {
    return direct_;
  }
  /**
   * <pre>
   * 方向
   * </pre>
   *
   * <code>.Ifaipb.DirectEnum direct = 3;</code>
   */
  public com.intellif.ifai.event.DirectEnum getDirect() {
    @SuppressWarnings("deprecation")
    com.intellif.ifai.event.DirectEnum result = com.intellif.ifai.event.DirectEnum.valueOf(direct_);
    return result == null ? com.intellif.ifai.event.DirectEnum.UNRECOGNIZED : result;
  }

  public static final int TRACK_ID_FIELD_NUMBER = 4;
  private int trackId_;
  /**
   * <pre>
   * </pre>
   *
   * <code>int32 track_id = 4;</code>
   */
  public int getTrackId() {
    return trackId_;
  }

  public static final int TIMESTAMP_FIELD_NUMBER = 5;
  private long timestamp_;
  /**
   * <pre>
   * 抓拍时间
   * </pre>
   *
   * <code>int64 timestamp = 5;</code>
   */
  public long getTimestamp() {
    return timestamp_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (preTrackId_ != 0) {
      output.writeInt32(1, preTrackId_);
    }
    if (ruleId_ != 0) {
      output.writeInt32(2, ruleId_);
    }
    if (direct_ != com.intellif.ifai.event.DirectEnum.DIRECT_IN.getNumber()) {
      output.writeEnum(3, direct_);
    }
    if (trackId_ != 0) {
      output.writeInt32(4, trackId_);
    }
    if (timestamp_ != 0L) {
      output.writeInt64(5, timestamp_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (preTrackId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, preTrackId_);
    }
    if (ruleId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, ruleId_);
    }
    if (direct_ != com.intellif.ifai.event.DirectEnum.DIRECT_IN.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(3, direct_);
    }
    if (trackId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, trackId_);
    }
    if (timestamp_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(5, timestamp_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.intellif.ifai.event.DirectEvents)) {
      return super.equals(obj);
    }
    com.intellif.ifai.event.DirectEvents other = (com.intellif.ifai.event.DirectEvents) obj;

    boolean result = true;
    result = result && (getPreTrackId()
        == other.getPreTrackId());
    result = result && (getRuleId()
        == other.getRuleId());
    result = result && direct_ == other.direct_;
    result = result && (getTrackId()
        == other.getTrackId());
    result = result && (getTimestamp()
        == other.getTimestamp());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + PRE_TRACK_ID_FIELD_NUMBER;
    hash = (53 * hash) + getPreTrackId();
    hash = (37 * hash) + RULE_ID_FIELD_NUMBER;
    hash = (53 * hash) + getRuleId();
    hash = (37 * hash) + DIRECT_FIELD_NUMBER;
    hash = (53 * hash) + direct_;
    hash = (37 * hash) + TRACK_ID_FIELD_NUMBER;
    hash = (53 * hash) + getTrackId();
    hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTimestamp());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.intellif.ifai.event.DirectEvents parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.intellif.ifai.event.DirectEvents parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.intellif.ifai.event.DirectEvents parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.intellif.ifai.event.DirectEvents parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.intellif.ifai.event.DirectEvents parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.intellif.ifai.event.DirectEvents parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.intellif.ifai.event.DirectEvents parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.intellif.ifai.event.DirectEvents parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.intellif.ifai.event.DirectEvents parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.intellif.ifai.event.DirectEvents parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.intellif.ifai.event.DirectEvents parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.intellif.ifai.event.DirectEvents parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.intellif.ifai.event.DirectEvents prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code Ifaipb.DirectEvents}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Ifaipb.DirectEvents)
      com.intellif.ifai.event.DirectEventsOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.intellif.ifai.event.Ifai.internal_static_Ifaipb_DirectEvents_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.intellif.ifai.event.Ifai.internal_static_Ifaipb_DirectEvents_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.intellif.ifai.event.DirectEvents.class, com.intellif.ifai.event.DirectEvents.Builder.class);
    }

    // Construct using com.intellif.ifai.event.DirectEvents.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      preTrackId_ = 0;

      ruleId_ = 0;

      direct_ = 0;

      trackId_ = 0;

      timestamp_ = 0L;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.intellif.ifai.event.Ifai.internal_static_Ifaipb_DirectEvents_descriptor;
    }

    @java.lang.Override
    public com.intellif.ifai.event.DirectEvents getDefaultInstanceForType() {
      return com.intellif.ifai.event.DirectEvents.getDefaultInstance();
    }

    @java.lang.Override
    public com.intellif.ifai.event.DirectEvents build() {
      com.intellif.ifai.event.DirectEvents result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.intellif.ifai.event.DirectEvents buildPartial() {
      com.intellif.ifai.event.DirectEvents result = new com.intellif.ifai.event.DirectEvents(this);
      result.preTrackId_ = preTrackId_;
      result.ruleId_ = ruleId_;
      result.direct_ = direct_;
      result.trackId_ = trackId_;
      result.timestamp_ = timestamp_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.intellif.ifai.event.DirectEvents) {
        return mergeFrom((com.intellif.ifai.event.DirectEvents)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.intellif.ifai.event.DirectEvents other) {
      if (other == com.intellif.ifai.event.DirectEvents.getDefaultInstance()) return this;
      if (other.getPreTrackId() != 0) {
        setPreTrackId(other.getPreTrackId());
      }
      if (other.getRuleId() != 0) {
        setRuleId(other.getRuleId());
      }
      if (other.direct_ != 0) {
        setDirectValue(other.getDirectValue());
      }
      if (other.getTrackId() != 0) {
        setTrackId(other.getTrackId());
      }
      if (other.getTimestamp() != 0L) {
        setTimestamp(other.getTimestamp());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.intellif.ifai.event.DirectEvents parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.intellif.ifai.event.DirectEvents) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int preTrackId_ ;
    /**
     * <pre>
     *旧trackid
     * </pre>
     *
     * <code>int32 pre_track_id = 1;</code>
     */
    public int getPreTrackId() {
      return preTrackId_;
    }
    /**
     * <pre>
     *旧trackid
     * </pre>
     *
     * <code>int32 pre_track_id = 1;</code>
     */
    public Builder setPreTrackId(int value) {
      
      preTrackId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *旧trackid
     * </pre>
     *
     * <code>int32 pre_track_id = 1;</code>
     */
    public Builder clearPreTrackId() {
      
      preTrackId_ = 0;
      onChanged();
      return this;
    }

    private int ruleId_ ;
    /**
     * <pre>
     *规则id
     * </pre>
     *
     * <code>int32 rule_id = 2;</code>
     */
    public int getRuleId() {
      return ruleId_;
    }
    /**
     * <pre>
     *规则id
     * </pre>
     *
     * <code>int32 rule_id = 2;</code>
     */
    public Builder setRuleId(int value) {
      
      ruleId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *规则id
     * </pre>
     *
     * <code>int32 rule_id = 2;</code>
     */
    public Builder clearRuleId() {
      
      ruleId_ = 0;
      onChanged();
      return this;
    }

    private int direct_ = 0;
    /**
     * <pre>
     * 方向
     * </pre>
     *
     * <code>.Ifaipb.DirectEnum direct = 3;</code>
     */
    public int getDirectValue() {
      return direct_;
    }
    /**
     * <pre>
     * 方向
     * </pre>
     *
     * <code>.Ifaipb.DirectEnum direct = 3;</code>
     */
    public Builder setDirectValue(int value) {
      direct_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 方向
     * </pre>
     *
     * <code>.Ifaipb.DirectEnum direct = 3;</code>
     */
    public com.intellif.ifai.event.DirectEnum getDirect() {
      @SuppressWarnings("deprecation")
      com.intellif.ifai.event.DirectEnum result = com.intellif.ifai.event.DirectEnum.valueOf(direct_);
      return result == null ? com.intellif.ifai.event.DirectEnum.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     * 方向
     * </pre>
     *
     * <code>.Ifaipb.DirectEnum direct = 3;</code>
     */
    public Builder setDirect(com.intellif.ifai.event.DirectEnum value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      direct_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 方向
     * </pre>
     *
     * <code>.Ifaipb.DirectEnum direct = 3;</code>
     */
    public Builder clearDirect() {
      
      direct_ = 0;
      onChanged();
      return this;
    }

    private int trackId_ ;
    /**
     * <pre>
     * </pre>
     *
     * <code>int32 track_id = 4;</code>
     */
    public int getTrackId() {
      return trackId_;
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>int32 track_id = 4;</code>
     */
    public Builder setTrackId(int value) {
      
      trackId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>int32 track_id = 4;</code>
     */
    public Builder clearTrackId() {
      
      trackId_ = 0;
      onChanged();
      return this;
    }

    private long timestamp_ ;
    /**
     * <pre>
     * 抓拍时间
     * </pre>
     *
     * <code>int64 timestamp = 5;</code>
     */
    public long getTimestamp() {
      return timestamp_;
    }
    /**
     * <pre>
     * 抓拍时间
     * </pre>
     *
     * <code>int64 timestamp = 5;</code>
     */
    public Builder setTimestamp(long value) {
      
      timestamp_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 抓拍时间
     * </pre>
     *
     * <code>int64 timestamp = 5;</code>
     */
    public Builder clearTimestamp() {
      
      timestamp_ = 0L;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:Ifaipb.DirectEvents)
  }

  // @@protoc_insertion_point(class_scope:Ifaipb.DirectEvents)
  private static final com.intellif.ifai.event.DirectEvents DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.intellif.ifai.event.DirectEvents();
  }

  public static com.intellif.ifai.event.DirectEvents getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<DirectEvents>
      PARSER = new com.google.protobuf.AbstractParser<DirectEvents>() {
    @java.lang.Override
    public DirectEvents parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new DirectEvents(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<DirectEvents> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<DirectEvents> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.intellif.ifai.event.DirectEvents getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

