// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: IfEvent.proto

package com.intellif.ifai.event;

public interface FaceMonitorResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Ifaipb.FaceMonitorResponse)
    com.google.protobuf.MessageOrBuilder {
}
