// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: IfEvent.proto

package com.intellif.ifai.event;

/**
 * Protobuf type {@code Ifaipb.FlowDirectEvents}
 */
public  final class FlowDirectEvents extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:Ifaipb.FlowDirectEvents)
    FlowDirectEventsOrBuilder {
private static final long serialVersionUID = 0L;
  // Use FlowDirectEvents.newBuilder() to construct.
  private FlowDirectEvents(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private FlowDirectEvents() {
    results_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private FlowDirectEvents(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              results_ = new java.util.ArrayList<com.intellif.ifai.event.FlowDirectEvents.Result>();
              mutable_bitField0_ |= 0x00000001;
            }
            results_.add(
                input.readMessage(com.intellif.ifai.event.FlowDirectEvents.Result.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        results_ = java.util.Collections.unmodifiableList(results_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.intellif.ifai.event.Ifai.internal_static_Ifaipb_FlowDirectEvents_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.intellif.ifai.event.Ifai.internal_static_Ifaipb_FlowDirectEvents_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.intellif.ifai.event.FlowDirectEvents.class, com.intellif.ifai.event.FlowDirectEvents.Builder.class);
  }

  public interface ResultOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Ifaipb.FlowDirectEvents.Result)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *规则id
     * </pre>
     *
     * <code>int32 rule_id = 1;</code>
     */
    int getRuleId();

    /**
     * <pre>
     * 方向
     * </pre>
     *
     * <code>.Ifaipb.DirectEnum direct = 2;</code>
     */
    int getDirectValue();
    /**
     * <pre>
     * 方向
     * </pre>
     *
     * <code>.Ifaipb.DirectEnum direct = 2;</code>
     */
    com.intellif.ifai.event.DirectEnum getDirect();

    /**
     * <pre>
     * 抓拍时间
     * </pre>
     *
     * <code>int64 timestamp = 3;</code>
     */
    long getTimestamp();
  }
  /**
   * Protobuf type {@code Ifaipb.FlowDirectEvents.Result}
   */
  public  static final class Result extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Ifaipb.FlowDirectEvents.Result)
      ResultOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Result.newBuilder() to construct.
    private Result(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Result() {
      ruleId_ = 0;
      direct_ = 0;
      timestamp_ = 0L;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Result(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              ruleId_ = input.readInt32();
              break;
            }
            case 16: {
              int rawValue = input.readEnum();

              direct_ = rawValue;
              break;
            }
            case 24: {

              timestamp_ = input.readInt64();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.intellif.ifai.event.Ifai.internal_static_Ifaipb_FlowDirectEvents_Result_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.intellif.ifai.event.Ifai.internal_static_Ifaipb_FlowDirectEvents_Result_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.intellif.ifai.event.FlowDirectEvents.Result.class, com.intellif.ifai.event.FlowDirectEvents.Result.Builder.class);
    }

    public static final int RULE_ID_FIELD_NUMBER = 1;
    private int ruleId_;
    /**
     * <pre>
     *规则id
     * </pre>
     *
     * <code>int32 rule_id = 1;</code>
     */
    public int getRuleId() {
      return ruleId_;
    }

    public static final int DIRECT_FIELD_NUMBER = 2;
    private int direct_;
    /**
     * <pre>
     * 方向
     * </pre>
     *
     * <code>.Ifaipb.DirectEnum direct = 2;</code>
     */
    public int getDirectValue() {
      return direct_;
    }
    /**
     * <pre>
     * 方向
     * </pre>
     *
     * <code>.Ifaipb.DirectEnum direct = 2;</code>
     */
    public com.intellif.ifai.event.DirectEnum getDirect() {
      @SuppressWarnings("deprecation")
      com.intellif.ifai.event.DirectEnum result = com.intellif.ifai.event.DirectEnum.valueOf(direct_);
      return result == null ? com.intellif.ifai.event.DirectEnum.UNRECOGNIZED : result;
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 3;
    private long timestamp_;
    /**
     * <pre>
     * 抓拍时间
     * </pre>
     *
     * <code>int64 timestamp = 3;</code>
     */
    public long getTimestamp() {
      return timestamp_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (ruleId_ != 0) {
        output.writeInt32(1, ruleId_);
      }
      if (direct_ != com.intellif.ifai.event.DirectEnum.DIRECT_IN.getNumber()) {
        output.writeEnum(2, direct_);
      }
      if (timestamp_ != 0L) {
        output.writeInt64(3, timestamp_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (ruleId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, ruleId_);
      }
      if (direct_ != com.intellif.ifai.event.DirectEnum.DIRECT_IN.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, direct_);
      }
      if (timestamp_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, timestamp_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.intellif.ifai.event.FlowDirectEvents.Result)) {
        return super.equals(obj);
      }
      com.intellif.ifai.event.FlowDirectEvents.Result other = (com.intellif.ifai.event.FlowDirectEvents.Result) obj;

      boolean result = true;
      result = result && (getRuleId()
          == other.getRuleId());
      result = result && direct_ == other.direct_;
      result = result && (getTimestamp()
          == other.getTimestamp());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + RULE_ID_FIELD_NUMBER;
      hash = (53 * hash) + getRuleId();
      hash = (37 * hash) + DIRECT_FIELD_NUMBER;
      hash = (53 * hash) + direct_;
      hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTimestamp());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.intellif.ifai.event.FlowDirectEvents.Result parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.intellif.ifai.event.FlowDirectEvents.Result parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.intellif.ifai.event.FlowDirectEvents.Result parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.intellif.ifai.event.FlowDirectEvents.Result parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.intellif.ifai.event.FlowDirectEvents.Result parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.intellif.ifai.event.FlowDirectEvents.Result parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.intellif.ifai.event.FlowDirectEvents.Result parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.intellif.ifai.event.FlowDirectEvents.Result parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.intellif.ifai.event.FlowDirectEvents.Result parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.intellif.ifai.event.FlowDirectEvents.Result parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.intellif.ifai.event.FlowDirectEvents.Result parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.intellif.ifai.event.FlowDirectEvents.Result parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.intellif.ifai.event.FlowDirectEvents.Result prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Ifaipb.FlowDirectEvents.Result}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Ifaipb.FlowDirectEvents.Result)
        com.intellif.ifai.event.FlowDirectEvents.ResultOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.intellif.ifai.event.Ifai.internal_static_Ifaipb_FlowDirectEvents_Result_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.intellif.ifai.event.Ifai.internal_static_Ifaipb_FlowDirectEvents_Result_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.intellif.ifai.event.FlowDirectEvents.Result.class, com.intellif.ifai.event.FlowDirectEvents.Result.Builder.class);
      }

      // Construct using com.intellif.ifai.event.FlowDirectEvents.Result.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        ruleId_ = 0;

        direct_ = 0;

        timestamp_ = 0L;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.intellif.ifai.event.Ifai.internal_static_Ifaipb_FlowDirectEvents_Result_descriptor;
      }

      @java.lang.Override
      public com.intellif.ifai.event.FlowDirectEvents.Result getDefaultInstanceForType() {
        return com.intellif.ifai.event.FlowDirectEvents.Result.getDefaultInstance();
      }

      @java.lang.Override
      public com.intellif.ifai.event.FlowDirectEvents.Result build() {
        com.intellif.ifai.event.FlowDirectEvents.Result result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.intellif.ifai.event.FlowDirectEvents.Result buildPartial() {
        com.intellif.ifai.event.FlowDirectEvents.Result result = new com.intellif.ifai.event.FlowDirectEvents.Result(this);
        result.ruleId_ = ruleId_;
        result.direct_ = direct_;
        result.timestamp_ = timestamp_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.intellif.ifai.event.FlowDirectEvents.Result) {
          return mergeFrom((com.intellif.ifai.event.FlowDirectEvents.Result)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.intellif.ifai.event.FlowDirectEvents.Result other) {
        if (other == com.intellif.ifai.event.FlowDirectEvents.Result.getDefaultInstance()) return this;
        if (other.getRuleId() != 0) {
          setRuleId(other.getRuleId());
        }
        if (other.direct_ != 0) {
          setDirectValue(other.getDirectValue());
        }
        if (other.getTimestamp() != 0L) {
          setTimestamp(other.getTimestamp());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.intellif.ifai.event.FlowDirectEvents.Result parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.intellif.ifai.event.FlowDirectEvents.Result) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int ruleId_ ;
      /**
       * <pre>
       *规则id
       * </pre>
       *
       * <code>int32 rule_id = 1;</code>
       */
      public int getRuleId() {
        return ruleId_;
      }
      /**
       * <pre>
       *规则id
       * </pre>
       *
       * <code>int32 rule_id = 1;</code>
       */
      public Builder setRuleId(int value) {
        
        ruleId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *规则id
       * </pre>
       *
       * <code>int32 rule_id = 1;</code>
       */
      public Builder clearRuleId() {
        
        ruleId_ = 0;
        onChanged();
        return this;
      }

      private int direct_ = 0;
      /**
       * <pre>
       * 方向
       * </pre>
       *
       * <code>.Ifaipb.DirectEnum direct = 2;</code>
       */
      public int getDirectValue() {
        return direct_;
      }
      /**
       * <pre>
       * 方向
       * </pre>
       *
       * <code>.Ifaipb.DirectEnum direct = 2;</code>
       */
      public Builder setDirectValue(int value) {
        direct_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 方向
       * </pre>
       *
       * <code>.Ifaipb.DirectEnum direct = 2;</code>
       */
      public com.intellif.ifai.event.DirectEnum getDirect() {
        @SuppressWarnings("deprecation")
        com.intellif.ifai.event.DirectEnum result = com.intellif.ifai.event.DirectEnum.valueOf(direct_);
        return result == null ? com.intellif.ifai.event.DirectEnum.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       * 方向
       * </pre>
       *
       * <code>.Ifaipb.DirectEnum direct = 2;</code>
       */
      public Builder setDirect(com.intellif.ifai.event.DirectEnum value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        direct_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 方向
       * </pre>
       *
       * <code>.Ifaipb.DirectEnum direct = 2;</code>
       */
      public Builder clearDirect() {
        
        direct_ = 0;
        onChanged();
        return this;
      }

      private long timestamp_ ;
      /**
       * <pre>
       * 抓拍时间
       * </pre>
       *
       * <code>int64 timestamp = 3;</code>
       */
      public long getTimestamp() {
        return timestamp_;
      }
      /**
       * <pre>
       * 抓拍时间
       * </pre>
       *
       * <code>int64 timestamp = 3;</code>
       */
      public Builder setTimestamp(long value) {
        
        timestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 抓拍时间
       * </pre>
       *
       * <code>int64 timestamp = 3;</code>
       */
      public Builder clearTimestamp() {
        
        timestamp_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Ifaipb.FlowDirectEvents.Result)
    }

    // @@protoc_insertion_point(class_scope:Ifaipb.FlowDirectEvents.Result)
    private static final com.intellif.ifai.event.FlowDirectEvents.Result DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.intellif.ifai.event.FlowDirectEvents.Result();
    }

    public static com.intellif.ifai.event.FlowDirectEvents.Result getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Result>
        PARSER = new com.google.protobuf.AbstractParser<Result>() {
      @java.lang.Override
      public Result parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Result(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Result> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Result> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.intellif.ifai.event.FlowDirectEvents.Result getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public static final int RESULTS_FIELD_NUMBER = 1;
  private java.util.List<com.intellif.ifai.event.FlowDirectEvents.Result> results_;
  /**
   * <code>repeated .Ifaipb.FlowDirectEvents.Result results = 1;</code>
   */
  public java.util.List<com.intellif.ifai.event.FlowDirectEvents.Result> getResultsList() {
    return results_;
  }
  /**
   * <code>repeated .Ifaipb.FlowDirectEvents.Result results = 1;</code>
   */
  public java.util.List<? extends com.intellif.ifai.event.FlowDirectEvents.ResultOrBuilder> 
      getResultsOrBuilderList() {
    return results_;
  }
  /**
   * <code>repeated .Ifaipb.FlowDirectEvents.Result results = 1;</code>
   */
  public int getResultsCount() {
    return results_.size();
  }
  /**
   * <code>repeated .Ifaipb.FlowDirectEvents.Result results = 1;</code>
   */
  public com.intellif.ifai.event.FlowDirectEvents.Result getResults(int index) {
    return results_.get(index);
  }
  /**
   * <code>repeated .Ifaipb.FlowDirectEvents.Result results = 1;</code>
   */
  public com.intellif.ifai.event.FlowDirectEvents.ResultOrBuilder getResultsOrBuilder(
      int index) {
    return results_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < results_.size(); i++) {
      output.writeMessage(1, results_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < results_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, results_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.intellif.ifai.event.FlowDirectEvents)) {
      return super.equals(obj);
    }
    com.intellif.ifai.event.FlowDirectEvents other = (com.intellif.ifai.event.FlowDirectEvents) obj;

    boolean result = true;
    result = result && getResultsList()
        .equals(other.getResultsList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getResultsCount() > 0) {
      hash = (37 * hash) + RESULTS_FIELD_NUMBER;
      hash = (53 * hash) + getResultsList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.intellif.ifai.event.FlowDirectEvents parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.intellif.ifai.event.FlowDirectEvents parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.intellif.ifai.event.FlowDirectEvents parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.intellif.ifai.event.FlowDirectEvents parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.intellif.ifai.event.FlowDirectEvents parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.intellif.ifai.event.FlowDirectEvents parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.intellif.ifai.event.FlowDirectEvents parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.intellif.ifai.event.FlowDirectEvents parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.intellif.ifai.event.FlowDirectEvents parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.intellif.ifai.event.FlowDirectEvents parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.intellif.ifai.event.FlowDirectEvents parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.intellif.ifai.event.FlowDirectEvents parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.intellif.ifai.event.FlowDirectEvents prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code Ifaipb.FlowDirectEvents}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Ifaipb.FlowDirectEvents)
      com.intellif.ifai.event.FlowDirectEventsOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.intellif.ifai.event.Ifai.internal_static_Ifaipb_FlowDirectEvents_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.intellif.ifai.event.Ifai.internal_static_Ifaipb_FlowDirectEvents_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.intellif.ifai.event.FlowDirectEvents.class, com.intellif.ifai.event.FlowDirectEvents.Builder.class);
    }

    // Construct using com.intellif.ifai.event.FlowDirectEvents.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getResultsFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (resultsBuilder_ == null) {
        results_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        resultsBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.intellif.ifai.event.Ifai.internal_static_Ifaipb_FlowDirectEvents_descriptor;
    }

    @java.lang.Override
    public com.intellif.ifai.event.FlowDirectEvents getDefaultInstanceForType() {
      return com.intellif.ifai.event.FlowDirectEvents.getDefaultInstance();
    }

    @java.lang.Override
    public com.intellif.ifai.event.FlowDirectEvents build() {
      com.intellif.ifai.event.FlowDirectEvents result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.intellif.ifai.event.FlowDirectEvents buildPartial() {
      com.intellif.ifai.event.FlowDirectEvents result = new com.intellif.ifai.event.FlowDirectEvents(this);
      int from_bitField0_ = bitField0_;
      if (resultsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          results_ = java.util.Collections.unmodifiableList(results_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.results_ = results_;
      } else {
        result.results_ = resultsBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.intellif.ifai.event.FlowDirectEvents) {
        return mergeFrom((com.intellif.ifai.event.FlowDirectEvents)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.intellif.ifai.event.FlowDirectEvents other) {
      if (other == com.intellif.ifai.event.FlowDirectEvents.getDefaultInstance()) return this;
      if (resultsBuilder_ == null) {
        if (!other.results_.isEmpty()) {
          if (results_.isEmpty()) {
            results_ = other.results_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureResultsIsMutable();
            results_.addAll(other.results_);
          }
          onChanged();
        }
      } else {
        if (!other.results_.isEmpty()) {
          if (resultsBuilder_.isEmpty()) {
            resultsBuilder_.dispose();
            resultsBuilder_ = null;
            results_ = other.results_;
            bitField0_ = (bitField0_ & ~0x00000001);
            resultsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getResultsFieldBuilder() : null;
          } else {
            resultsBuilder_.addAllMessages(other.results_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.intellif.ifai.event.FlowDirectEvents parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.intellif.ifai.event.FlowDirectEvents) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<com.intellif.ifai.event.FlowDirectEvents.Result> results_ =
      java.util.Collections.emptyList();
    private void ensureResultsIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        results_ = new java.util.ArrayList<com.intellif.ifai.event.FlowDirectEvents.Result>(results_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.intellif.ifai.event.FlowDirectEvents.Result, com.intellif.ifai.event.FlowDirectEvents.Result.Builder, com.intellif.ifai.event.FlowDirectEvents.ResultOrBuilder> resultsBuilder_;

    /**
     * <code>repeated .Ifaipb.FlowDirectEvents.Result results = 1;</code>
     */
    public java.util.List<com.intellif.ifai.event.FlowDirectEvents.Result> getResultsList() {
      if (resultsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(results_);
      } else {
        return resultsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .Ifaipb.FlowDirectEvents.Result results = 1;</code>
     */
    public int getResultsCount() {
      if (resultsBuilder_ == null) {
        return results_.size();
      } else {
        return resultsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .Ifaipb.FlowDirectEvents.Result results = 1;</code>
     */
    public com.intellif.ifai.event.FlowDirectEvents.Result getResults(int index) {
      if (resultsBuilder_ == null) {
        return results_.get(index);
      } else {
        return resultsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .Ifaipb.FlowDirectEvents.Result results = 1;</code>
     */
    public Builder setResults(
        int index, com.intellif.ifai.event.FlowDirectEvents.Result value) {
      if (resultsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureResultsIsMutable();
        results_.set(index, value);
        onChanged();
      } else {
        resultsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Ifaipb.FlowDirectEvents.Result results = 1;</code>
     */
    public Builder setResults(
        int index, com.intellif.ifai.event.FlowDirectEvents.Result.Builder builderForValue) {
      if (resultsBuilder_ == null) {
        ensureResultsIsMutable();
        results_.set(index, builderForValue.build());
        onChanged();
      } else {
        resultsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Ifaipb.FlowDirectEvents.Result results = 1;</code>
     */
    public Builder addResults(com.intellif.ifai.event.FlowDirectEvents.Result value) {
      if (resultsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureResultsIsMutable();
        results_.add(value);
        onChanged();
      } else {
        resultsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .Ifaipb.FlowDirectEvents.Result results = 1;</code>
     */
    public Builder addResults(
        int index, com.intellif.ifai.event.FlowDirectEvents.Result value) {
      if (resultsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureResultsIsMutable();
        results_.add(index, value);
        onChanged();
      } else {
        resultsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Ifaipb.FlowDirectEvents.Result results = 1;</code>
     */
    public Builder addResults(
        com.intellif.ifai.event.FlowDirectEvents.Result.Builder builderForValue) {
      if (resultsBuilder_ == null) {
        ensureResultsIsMutable();
        results_.add(builderForValue.build());
        onChanged();
      } else {
        resultsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Ifaipb.FlowDirectEvents.Result results = 1;</code>
     */
    public Builder addResults(
        int index, com.intellif.ifai.event.FlowDirectEvents.Result.Builder builderForValue) {
      if (resultsBuilder_ == null) {
        ensureResultsIsMutable();
        results_.add(index, builderForValue.build());
        onChanged();
      } else {
        resultsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Ifaipb.FlowDirectEvents.Result results = 1;</code>
     */
    public Builder addAllResults(
        java.lang.Iterable<? extends com.intellif.ifai.event.FlowDirectEvents.Result> values) {
      if (resultsBuilder_ == null) {
        ensureResultsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, results_);
        onChanged();
      } else {
        resultsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .Ifaipb.FlowDirectEvents.Result results = 1;</code>
     */
    public Builder clearResults() {
      if (resultsBuilder_ == null) {
        results_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        resultsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .Ifaipb.FlowDirectEvents.Result results = 1;</code>
     */
    public Builder removeResults(int index) {
      if (resultsBuilder_ == null) {
        ensureResultsIsMutable();
        results_.remove(index);
        onChanged();
      } else {
        resultsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .Ifaipb.FlowDirectEvents.Result results = 1;</code>
     */
    public com.intellif.ifai.event.FlowDirectEvents.Result.Builder getResultsBuilder(
        int index) {
      return getResultsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .Ifaipb.FlowDirectEvents.Result results = 1;</code>
     */
    public com.intellif.ifai.event.FlowDirectEvents.ResultOrBuilder getResultsOrBuilder(
        int index) {
      if (resultsBuilder_ == null) {
        return results_.get(index);  } else {
        return resultsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .Ifaipb.FlowDirectEvents.Result results = 1;</code>
     */
    public java.util.List<? extends com.intellif.ifai.event.FlowDirectEvents.ResultOrBuilder> 
         getResultsOrBuilderList() {
      if (resultsBuilder_ != null) {
        return resultsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(results_);
      }
    }
    /**
     * <code>repeated .Ifaipb.FlowDirectEvents.Result results = 1;</code>
     */
    public com.intellif.ifai.event.FlowDirectEvents.Result.Builder addResultsBuilder() {
      return getResultsFieldBuilder().addBuilder(
          com.intellif.ifai.event.FlowDirectEvents.Result.getDefaultInstance());
    }
    /**
     * <code>repeated .Ifaipb.FlowDirectEvents.Result results = 1;</code>
     */
    public com.intellif.ifai.event.FlowDirectEvents.Result.Builder addResultsBuilder(
        int index) {
      return getResultsFieldBuilder().addBuilder(
          index, com.intellif.ifai.event.FlowDirectEvents.Result.getDefaultInstance());
    }
    /**
     * <code>repeated .Ifaipb.FlowDirectEvents.Result results = 1;</code>
     */
    public java.util.List<com.intellif.ifai.event.FlowDirectEvents.Result.Builder> 
         getResultsBuilderList() {
      return getResultsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.intellif.ifai.event.FlowDirectEvents.Result, com.intellif.ifai.event.FlowDirectEvents.Result.Builder, com.intellif.ifai.event.FlowDirectEvents.ResultOrBuilder> 
        getResultsFieldBuilder() {
      if (resultsBuilder_ == null) {
        resultsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.intellif.ifai.event.FlowDirectEvents.Result, com.intellif.ifai.event.FlowDirectEvents.Result.Builder, com.intellif.ifai.event.FlowDirectEvents.ResultOrBuilder>(
                results_,
                ((bitField0_ & 0x00000001) == 0x00000001),
                getParentForChildren(),
                isClean());
        results_ = null;
      }
      return resultsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:Ifaipb.FlowDirectEvents)
  }

  // @@protoc_insertion_point(class_scope:Ifaipb.FlowDirectEvents)
  private static final com.intellif.ifai.event.FlowDirectEvents DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.intellif.ifai.event.FlowDirectEvents();
  }

  public static com.intellif.ifai.event.FlowDirectEvents getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<FlowDirectEvents>
      PARSER = new com.google.protobuf.AbstractParser<FlowDirectEvents>() {
    @java.lang.Override
    public FlowDirectEvents parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new FlowDirectEvents(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<FlowDirectEvents> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<FlowDirectEvents> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.intellif.ifai.event.FlowDirectEvents getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

