// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: IfEvent.proto

package com.intellif.ifai.event;

public interface GetCurrentFaceRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Ifaipb.GetCurrentFaceRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *抓拍数量
   * </pre>
   *
   * <code>int32 num = 1;</code>
   */
  int getNum();
}
