// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: IfEvent.proto

package com.intellif.ifai.event;

public interface UnsubscribeRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Ifaipb.UnsubscribeRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 订阅标识
   * </pre>
   *
   * <code>int32 subscription_id = 1;</code>
   */
  int getSubscriptionId();
}
