// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: IfMeeting.proto

package com.intellif.ifai.meeting;

public interface AddMeetingRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Ifaipb.AddMeetingRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 会议id
   * </pre>
   *
   * <code>int64 meeting_id = 1;</code>
   */
  long getMeetingId();

  /**
   * <pre>
   * 会议名称
   * </pre>
   *
   * <code>string meeting_name = 2;</code>
   */
  java.lang.String getMeetingName();
  /**
   * <pre>
   * 会议名称
   * </pre>
   *
   * <code>string meeting_name = 2;</code>
   */
  com.google.protobuf.ByteString
      getMeetingNameBytes();

  /**
   * <pre>
   * 会议室名称
   * </pre>
   *
   * <code>string meeting_room_name = 3;</code>
   */
  java.lang.String getMeetingRoomName();
  /**
   * <pre>
   * 会议室名称
   * </pre>
   *
   * <code>string meeting_room_name = 3;</code>
   */
  com.google.protobuf.ByteString
      getMeetingRoomNameBytes();

  /**
   * <pre>
   * 会议开始时间
   * </pre>
   *
   * <code>.Ifaipb.DateTime start = 4;</code>
   */
  boolean hasStart();
  /**
   * <pre>
   * 会议开始时间
   * </pre>
   *
   * <code>.Ifaipb.DateTime start = 4;</code>
   */
  com.intellif.ifai.common.DateTime getStart();
  /**
   * <pre>
   * 会议开始时间
   * </pre>
   *
   * <code>.Ifaipb.DateTime start = 4;</code>
   */
  com.intellif.ifai.common.DateTimeOrBuilder getStartOrBuilder();

  /**
   * <pre>
   * 会议结束时间
   * </pre>
   *
   * <code>.Ifaipb.DateTime stop = 5;</code>
   */
  boolean hasStop();
  /**
   * <pre>
   * 会议结束时间
   * </pre>
   *
   * <code>.Ifaipb.DateTime stop = 5;</code>
   */
  com.intellif.ifai.common.DateTime getStop();
  /**
   * <pre>
   * 会议结束时间
   * </pre>
   *
   * <code>.Ifaipb.DateTime stop = 5;</code>
   */
  com.intellif.ifai.common.DateTimeOrBuilder getStopOrBuilder();

  /**
   * <pre>
   * 与会人数
   * </pre>
   *
   * <code>int32 attend_num = 6;</code>
   */
  int getAttendNum();

  /**
   * <pre>
   * 发起人名称
   * </pre>
   *
   * <code>string promoter_name = 7;</code>
   */
  java.lang.String getPromoterName();
  /**
   * <pre>
   * 发起人名称
   * </pre>
   *
   * <code>string promoter_name = 7;</code>
   */
  com.google.protobuf.ByteString
      getPromoterNameBytes();
}
