// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: IfAnalytics.proto

package com.intellif.ifai.face;

public interface DeleteRuleResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Ifaipb.DeleteRuleResponse)
    com.google.protobuf.MessageOrBuilder {
}
