// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: IfAnalytics.proto

package com.intellif.ifai.face;

public interface GetGuardTimeRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Ifaipb.GetGuardTimeRequest)
    com.google.protobuf.MessageOrBuilder {
}
