// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: IfCanteen.proto

package com.intellif.ifai.canteen;

public interface IdentifyCanteenPersonRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Ifaipb.IdentifyCanteenPersonRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *人员id
   * </pre>
   *
   * <code>string person_id = 1;</code>
   */
  java.lang.String getPersonId();
  /**
   * <pre>
   *人员id
   * </pre>
   *
   * <code>string person_id = 1;</code>
   */
  com.google.protobuf.ByteString
      getPersonIdBytes();
}
