// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: IfFaceDatabase.proto

package com.intellif.ifai.facedb;

public interface CancelFaceDatabaseExportResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Ifaipb.CancelFaceDatabaseExportResponse)
    com.google.protobuf.MessageOrBuilder {
}
