// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: IfFaceDatabase.proto

package com.intellif.ifai.facedb;

/**
 * Protobuf type {@code Ifaipb.FaceCommand}
 */
public  final class FaceCommand extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:Ifaipb.FaceCommand)
    FaceCommandOrBuilder {
private static final long serialVersionUID = 0L;
  // Use FaceCommand.newBuilder() to construct.
  private FaceCommand(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private FaceCommand() {
    id_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private FaceCommand(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            id_ = input.readInt32();
            break;
          }
          case 18: {
            com.intellif.ifai.facedb.AddPersonByFeatureRequest.Builder subBuilder = null;
            if (typeCase_ == 2) {
              subBuilder = ((com.intellif.ifai.facedb.AddPersonByFeatureRequest) type_).toBuilder();
            }
            type_ =
                input.readMessage(com.intellif.ifai.facedb.AddPersonByFeatureRequest.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((com.intellif.ifai.facedb.AddPersonByFeatureRequest) type_);
              type_ = subBuilder.buildPartial();
            }
            typeCase_ = 2;
            break;
          }
          case 26: {
            com.intellif.ifai.facedb.DeletePersonRequest.Builder subBuilder = null;
            if (typeCase_ == 3) {
              subBuilder = ((com.intellif.ifai.facedb.DeletePersonRequest) type_).toBuilder();
            }
            type_ =
                input.readMessage(com.intellif.ifai.facedb.DeletePersonRequest.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((com.intellif.ifai.facedb.DeletePersonRequest) type_);
              type_ = subBuilder.buildPartial();
            }
            typeCase_ = 3;
            break;
          }
          case 34: {
            com.intellif.ifai.facedb.SetPersonRequest.Builder subBuilder = null;
            if (typeCase_ == 4) {
              subBuilder = ((com.intellif.ifai.facedb.SetPersonRequest) type_).toBuilder();
            }
            type_ =
                input.readMessage(com.intellif.ifai.facedb.SetPersonRequest.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((com.intellif.ifai.facedb.SetPersonRequest) type_);
              type_ = subBuilder.buildPartial();
            }
            typeCase_ = 4;
            break;
          }
          case 42: {
            com.intellif.ifai.facedb.AddPersonRequest.Builder subBuilder = null;
            if (typeCase_ == 5) {
              subBuilder = ((com.intellif.ifai.facedb.AddPersonRequest) type_).toBuilder();
            }
            type_ =
                input.readMessage(com.intellif.ifai.facedb.AddPersonRequest.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((com.intellif.ifai.facedb.AddPersonRequest) type_);
              type_ = subBuilder.buildPartial();
            }
            typeCase_ = 5;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.intellif.ifai.facedb.Ifai.internal_static_Ifaipb_FaceCommand_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.intellif.ifai.facedb.Ifai.internal_static_Ifaipb_FaceCommand_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.intellif.ifai.facedb.FaceCommand.class, com.intellif.ifai.facedb.FaceCommand.Builder.class);
  }

  private int typeCase_ = 0;
  private java.lang.Object type_;
  public enum TypeCase
      implements com.google.protobuf.Internal.EnumLite {
    FEATURE_REQUEST(2),
    DELETION_REQUEST(3),
    MODIFICATION_REQUEST(4),
    IMAGE_REQUEST(5),
    TYPE_NOT_SET(0);
    private final int value;
    private TypeCase(int value) {
      this.value = value;
    }
    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static TypeCase valueOf(int value) {
      return forNumber(value);
    }

    public static TypeCase forNumber(int value) {
      switch (value) {
        case 2: return FEATURE_REQUEST;
        case 3: return DELETION_REQUEST;
        case 4: return MODIFICATION_REQUEST;
        case 5: return IMAGE_REQUEST;
        case 0: return TYPE_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public TypeCase
  getTypeCase() {
    return TypeCase.forNumber(
        typeCase_);
  }

  public static final int ID_FIELD_NUMBER = 1;
  private int id_;
  /**
   * <pre>
   * id
   * </pre>
   *
   * <code>int32 id = 1;</code>
   */
  public int getId() {
    return id_;
  }

  public static final int FEATURE_REQUEST_FIELD_NUMBER = 2;
  /**
   * <pre>
   * 特征值授权
   * </pre>
   *
   * <code>.Ifaipb.AddPersonByFeatureRequest feature_request = 2;</code>
   */
  public boolean hasFeatureRequest() {
    return typeCase_ == 2;
  }
  /**
   * <pre>
   * 特征值授权
   * </pre>
   *
   * <code>.Ifaipb.AddPersonByFeatureRequest feature_request = 2;</code>
   */
  public com.intellif.ifai.facedb.AddPersonByFeatureRequest getFeatureRequest() {
    if (typeCase_ == 2) {
       return (com.intellif.ifai.facedb.AddPersonByFeatureRequest) type_;
    }
    return com.intellif.ifai.facedb.AddPersonByFeatureRequest.getDefaultInstance();
  }
  /**
   * <pre>
   * 特征值授权
   * </pre>
   *
   * <code>.Ifaipb.AddPersonByFeatureRequest feature_request = 2;</code>
   */
  public com.intellif.ifai.facedb.AddPersonByFeatureRequestOrBuilder getFeatureRequestOrBuilder() {
    if (typeCase_ == 2) {
       return (com.intellif.ifai.facedb.AddPersonByFeatureRequest) type_;
    }
    return com.intellif.ifai.facedb.AddPersonByFeatureRequest.getDefaultInstance();
  }

  public static final int DELETION_REQUEST_FIELD_NUMBER = 3;
  /**
   * <pre>
   * 删除授权
   * </pre>
   *
   * <code>.Ifaipb.DeletePersonRequest deletion_request = 3;</code>
   */
  public boolean hasDeletionRequest() {
    return typeCase_ == 3;
  }
  /**
   * <pre>
   * 删除授权
   * </pre>
   *
   * <code>.Ifaipb.DeletePersonRequest deletion_request = 3;</code>
   */
  public com.intellif.ifai.facedb.DeletePersonRequest getDeletionRequest() {
    if (typeCase_ == 3) {
       return (com.intellif.ifai.facedb.DeletePersonRequest) type_;
    }
    return com.intellif.ifai.facedb.DeletePersonRequest.getDefaultInstance();
  }
  /**
   * <pre>
   * 删除授权
   * </pre>
   *
   * <code>.Ifaipb.DeletePersonRequest deletion_request = 3;</code>
   */
  public com.intellif.ifai.facedb.DeletePersonRequestOrBuilder getDeletionRequestOrBuilder() {
    if (typeCase_ == 3) {
       return (com.intellif.ifai.facedb.DeletePersonRequest) type_;
    }
    return com.intellif.ifai.facedb.DeletePersonRequest.getDefaultInstance();
  }

  public static final int MODIFICATION_REQUEST_FIELD_NUMBER = 4;
  /**
   * <pre>
   * 修改人员信息
   * </pre>
   *
   * <code>.Ifaipb.SetPersonRequest modification_request = 4;</code>
   */
  public boolean hasModificationRequest() {
    return typeCase_ == 4;
  }
  /**
   * <pre>
   * 修改人员信息
   * </pre>
   *
   * <code>.Ifaipb.SetPersonRequest modification_request = 4;</code>
   */
  public com.intellif.ifai.facedb.SetPersonRequest getModificationRequest() {
    if (typeCase_ == 4) {
       return (com.intellif.ifai.facedb.SetPersonRequest) type_;
    }
    return com.intellif.ifai.facedb.SetPersonRequest.getDefaultInstance();
  }
  /**
   * <pre>
   * 修改人员信息
   * </pre>
   *
   * <code>.Ifaipb.SetPersonRequest modification_request = 4;</code>
   */
  public com.intellif.ifai.facedb.SetPersonRequestOrBuilder getModificationRequestOrBuilder() {
    if (typeCase_ == 4) {
       return (com.intellif.ifai.facedb.SetPersonRequest) type_;
    }
    return com.intellif.ifai.facedb.SetPersonRequest.getDefaultInstance();
  }

  public static final int IMAGE_REQUEST_FIELD_NUMBER = 5;
  /**
   * <pre>
   * 人脸照片授权
   * </pre>
   *
   * <code>.Ifaipb.AddPersonRequest image_request = 5;</code>
   */
  public boolean hasImageRequest() {
    return typeCase_ == 5;
  }
  /**
   * <pre>
   * 人脸照片授权
   * </pre>
   *
   * <code>.Ifaipb.AddPersonRequest image_request = 5;</code>
   */
  public com.intellif.ifai.facedb.AddPersonRequest getImageRequest() {
    if (typeCase_ == 5) {
       return (com.intellif.ifai.facedb.AddPersonRequest) type_;
    }
    return com.intellif.ifai.facedb.AddPersonRequest.getDefaultInstance();
  }
  /**
   * <pre>
   * 人脸照片授权
   * </pre>
   *
   * <code>.Ifaipb.AddPersonRequest image_request = 5;</code>
   */
  public com.intellif.ifai.facedb.AddPersonRequestOrBuilder getImageRequestOrBuilder() {
    if (typeCase_ == 5) {
       return (com.intellif.ifai.facedb.AddPersonRequest) type_;
    }
    return com.intellif.ifai.facedb.AddPersonRequest.getDefaultInstance();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (id_ != 0) {
      output.writeInt32(1, id_);
    }
    if (typeCase_ == 2) {
      output.writeMessage(2, (com.intellif.ifai.facedb.AddPersonByFeatureRequest) type_);
    }
    if (typeCase_ == 3) {
      output.writeMessage(3, (com.intellif.ifai.facedb.DeletePersonRequest) type_);
    }
    if (typeCase_ == 4) {
      output.writeMessage(4, (com.intellif.ifai.facedb.SetPersonRequest) type_);
    }
    if (typeCase_ == 5) {
      output.writeMessage(5, (com.intellif.ifai.facedb.AddPersonRequest) type_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (id_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, id_);
    }
    if (typeCase_ == 2) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, (com.intellif.ifai.facedb.AddPersonByFeatureRequest) type_);
    }
    if (typeCase_ == 3) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, (com.intellif.ifai.facedb.DeletePersonRequest) type_);
    }
    if (typeCase_ == 4) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, (com.intellif.ifai.facedb.SetPersonRequest) type_);
    }
    if (typeCase_ == 5) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, (com.intellif.ifai.facedb.AddPersonRequest) type_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.intellif.ifai.facedb.FaceCommand)) {
      return super.equals(obj);
    }
    com.intellif.ifai.facedb.FaceCommand other = (com.intellif.ifai.facedb.FaceCommand) obj;

    boolean result = true;
    result = result && (getId()
        == other.getId());
    result = result && getTypeCase().equals(
        other.getTypeCase());
    if (!result) return false;
    switch (typeCase_) {
      case 2:
        result = result && getFeatureRequest()
            .equals(other.getFeatureRequest());
        break;
      case 3:
        result = result && getDeletionRequest()
            .equals(other.getDeletionRequest());
        break;
      case 4:
        result = result && getModificationRequest()
            .equals(other.getModificationRequest());
        break;
      case 5:
        result = result && getImageRequest()
            .equals(other.getImageRequest());
        break;
      case 0:
      default:
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId();
    switch (typeCase_) {
      case 2:
        hash = (37 * hash) + FEATURE_REQUEST_FIELD_NUMBER;
        hash = (53 * hash) + getFeatureRequest().hashCode();
        break;
      case 3:
        hash = (37 * hash) + DELETION_REQUEST_FIELD_NUMBER;
        hash = (53 * hash) + getDeletionRequest().hashCode();
        break;
      case 4:
        hash = (37 * hash) + MODIFICATION_REQUEST_FIELD_NUMBER;
        hash = (53 * hash) + getModificationRequest().hashCode();
        break;
      case 5:
        hash = (37 * hash) + IMAGE_REQUEST_FIELD_NUMBER;
        hash = (53 * hash) + getImageRequest().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.intellif.ifai.facedb.FaceCommand parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.intellif.ifai.facedb.FaceCommand parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.intellif.ifai.facedb.FaceCommand parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.intellif.ifai.facedb.FaceCommand parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.intellif.ifai.facedb.FaceCommand parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.intellif.ifai.facedb.FaceCommand parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.intellif.ifai.facedb.FaceCommand parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.intellif.ifai.facedb.FaceCommand parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.intellif.ifai.facedb.FaceCommand parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.intellif.ifai.facedb.FaceCommand parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.intellif.ifai.facedb.FaceCommand parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.intellif.ifai.facedb.FaceCommand parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.intellif.ifai.facedb.FaceCommand prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code Ifaipb.FaceCommand}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Ifaipb.FaceCommand)
      com.intellif.ifai.facedb.FaceCommandOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.intellif.ifai.facedb.Ifai.internal_static_Ifaipb_FaceCommand_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.intellif.ifai.facedb.Ifai.internal_static_Ifaipb_FaceCommand_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.intellif.ifai.facedb.FaceCommand.class, com.intellif.ifai.facedb.FaceCommand.Builder.class);
    }

    // Construct using com.intellif.ifai.facedb.FaceCommand.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      id_ = 0;

      typeCase_ = 0;
      type_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.intellif.ifai.facedb.Ifai.internal_static_Ifaipb_FaceCommand_descriptor;
    }

    @java.lang.Override
    public com.intellif.ifai.facedb.FaceCommand getDefaultInstanceForType() {
      return com.intellif.ifai.facedb.FaceCommand.getDefaultInstance();
    }

    @java.lang.Override
    public com.intellif.ifai.facedb.FaceCommand build() {
      com.intellif.ifai.facedb.FaceCommand result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.intellif.ifai.facedb.FaceCommand buildPartial() {
      com.intellif.ifai.facedb.FaceCommand result = new com.intellif.ifai.facedb.FaceCommand(this);
      result.id_ = id_;
      if (typeCase_ == 2) {
        if (featureRequestBuilder_ == null) {
          result.type_ = type_;
        } else {
          result.type_ = featureRequestBuilder_.build();
        }
      }
      if (typeCase_ == 3) {
        if (deletionRequestBuilder_ == null) {
          result.type_ = type_;
        } else {
          result.type_ = deletionRequestBuilder_.build();
        }
      }
      if (typeCase_ == 4) {
        if (modificationRequestBuilder_ == null) {
          result.type_ = type_;
        } else {
          result.type_ = modificationRequestBuilder_.build();
        }
      }
      if (typeCase_ == 5) {
        if (imageRequestBuilder_ == null) {
          result.type_ = type_;
        } else {
          result.type_ = imageRequestBuilder_.build();
        }
      }
      result.typeCase_ = typeCase_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.intellif.ifai.facedb.FaceCommand) {
        return mergeFrom((com.intellif.ifai.facedb.FaceCommand)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.intellif.ifai.facedb.FaceCommand other) {
      if (other == com.intellif.ifai.facedb.FaceCommand.getDefaultInstance()) return this;
      if (other.getId() != 0) {
        setId(other.getId());
      }
      switch (other.getTypeCase()) {
        case FEATURE_REQUEST: {
          mergeFeatureRequest(other.getFeatureRequest());
          break;
        }
        case DELETION_REQUEST: {
          mergeDeletionRequest(other.getDeletionRequest());
          break;
        }
        case MODIFICATION_REQUEST: {
          mergeModificationRequest(other.getModificationRequest());
          break;
        }
        case IMAGE_REQUEST: {
          mergeImageRequest(other.getImageRequest());
          break;
        }
        case TYPE_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.intellif.ifai.facedb.FaceCommand parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.intellif.ifai.facedb.FaceCommand) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int typeCase_ = 0;
    private java.lang.Object type_;
    public TypeCase
        getTypeCase() {
      return TypeCase.forNumber(
          typeCase_);
    }

    public Builder clearType() {
      typeCase_ = 0;
      type_ = null;
      onChanged();
      return this;
    }


    private int id_ ;
    /**
     * <pre>
     * id
     * </pre>
     *
     * <code>int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }
    /**
     * <pre>
     * id
     * </pre>
     *
     * <code>int32 id = 1;</code>
     */
    public Builder setId(int value) {
      
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * id
     * </pre>
     *
     * <code>int32 id = 1;</code>
     */
    public Builder clearId() {
      
      id_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        com.intellif.ifai.facedb.AddPersonByFeatureRequest, com.intellif.ifai.facedb.AddPersonByFeatureRequest.Builder, com.intellif.ifai.facedb.AddPersonByFeatureRequestOrBuilder> featureRequestBuilder_;
    /**
     * <pre>
     * 特征值授权
     * </pre>
     *
     * <code>.Ifaipb.AddPersonByFeatureRequest feature_request = 2;</code>
     */
    public boolean hasFeatureRequest() {
      return typeCase_ == 2;
    }
    /**
     * <pre>
     * 特征值授权
     * </pre>
     *
     * <code>.Ifaipb.AddPersonByFeatureRequest feature_request = 2;</code>
     */
    public com.intellif.ifai.facedb.AddPersonByFeatureRequest getFeatureRequest() {
      if (featureRequestBuilder_ == null) {
        if (typeCase_ == 2) {
          return (com.intellif.ifai.facedb.AddPersonByFeatureRequest) type_;
        }
        return com.intellif.ifai.facedb.AddPersonByFeatureRequest.getDefaultInstance();
      } else {
        if (typeCase_ == 2) {
          return featureRequestBuilder_.getMessage();
        }
        return com.intellif.ifai.facedb.AddPersonByFeatureRequest.getDefaultInstance();
      }
    }
    /**
     * <pre>
     * 特征值授权
     * </pre>
     *
     * <code>.Ifaipb.AddPersonByFeatureRequest feature_request = 2;</code>
     */
    public Builder setFeatureRequest(com.intellif.ifai.facedb.AddPersonByFeatureRequest value) {
      if (featureRequestBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        type_ = value;
        onChanged();
      } else {
        featureRequestBuilder_.setMessage(value);
      }
      typeCase_ = 2;
      return this;
    }
    /**
     * <pre>
     * 特征值授权
     * </pre>
     *
     * <code>.Ifaipb.AddPersonByFeatureRequest feature_request = 2;</code>
     */
    public Builder setFeatureRequest(
        com.intellif.ifai.facedb.AddPersonByFeatureRequest.Builder builderForValue) {
      if (featureRequestBuilder_ == null) {
        type_ = builderForValue.build();
        onChanged();
      } else {
        featureRequestBuilder_.setMessage(builderForValue.build());
      }
      typeCase_ = 2;
      return this;
    }
    /**
     * <pre>
     * 特征值授权
     * </pre>
     *
     * <code>.Ifaipb.AddPersonByFeatureRequest feature_request = 2;</code>
     */
    public Builder mergeFeatureRequest(com.intellif.ifai.facedb.AddPersonByFeatureRequest value) {
      if (featureRequestBuilder_ == null) {
        if (typeCase_ == 2 &&
            type_ != com.intellif.ifai.facedb.AddPersonByFeatureRequest.getDefaultInstance()) {
          type_ = com.intellif.ifai.facedb.AddPersonByFeatureRequest.newBuilder((com.intellif.ifai.facedb.AddPersonByFeatureRequest) type_)
              .mergeFrom(value).buildPartial();
        } else {
          type_ = value;
        }
        onChanged();
      } else {
        if (typeCase_ == 2) {
          featureRequestBuilder_.mergeFrom(value);
        }
        featureRequestBuilder_.setMessage(value);
      }
      typeCase_ = 2;
      return this;
    }
    /**
     * <pre>
     * 特征值授权
     * </pre>
     *
     * <code>.Ifaipb.AddPersonByFeatureRequest feature_request = 2;</code>
     */
    public Builder clearFeatureRequest() {
      if (featureRequestBuilder_ == null) {
        if (typeCase_ == 2) {
          typeCase_ = 0;
          type_ = null;
          onChanged();
        }
      } else {
        if (typeCase_ == 2) {
          typeCase_ = 0;
          type_ = null;
        }
        featureRequestBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * 特征值授权
     * </pre>
     *
     * <code>.Ifaipb.AddPersonByFeatureRequest feature_request = 2;</code>
     */
    public com.intellif.ifai.facedb.AddPersonByFeatureRequest.Builder getFeatureRequestBuilder() {
      return getFeatureRequestFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * 特征值授权
     * </pre>
     *
     * <code>.Ifaipb.AddPersonByFeatureRequest feature_request = 2;</code>
     */
    public com.intellif.ifai.facedb.AddPersonByFeatureRequestOrBuilder getFeatureRequestOrBuilder() {
      if ((typeCase_ == 2) && (featureRequestBuilder_ != null)) {
        return featureRequestBuilder_.getMessageOrBuilder();
      } else {
        if (typeCase_ == 2) {
          return (com.intellif.ifai.facedb.AddPersonByFeatureRequest) type_;
        }
        return com.intellif.ifai.facedb.AddPersonByFeatureRequest.getDefaultInstance();
      }
    }
    /**
     * <pre>
     * 特征值授权
     * </pre>
     *
     * <code>.Ifaipb.AddPersonByFeatureRequest feature_request = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.intellif.ifai.facedb.AddPersonByFeatureRequest, com.intellif.ifai.facedb.AddPersonByFeatureRequest.Builder, com.intellif.ifai.facedb.AddPersonByFeatureRequestOrBuilder> 
        getFeatureRequestFieldBuilder() {
      if (featureRequestBuilder_ == null) {
        if (!(typeCase_ == 2)) {
          type_ = com.intellif.ifai.facedb.AddPersonByFeatureRequest.getDefaultInstance();
        }
        featureRequestBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.intellif.ifai.facedb.AddPersonByFeatureRequest, com.intellif.ifai.facedb.AddPersonByFeatureRequest.Builder, com.intellif.ifai.facedb.AddPersonByFeatureRequestOrBuilder>(
                (com.intellif.ifai.facedb.AddPersonByFeatureRequest) type_,
                getParentForChildren(),
                isClean());
        type_ = null;
      }
      typeCase_ = 2;
      onChanged();;
      return featureRequestBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        com.intellif.ifai.facedb.DeletePersonRequest, com.intellif.ifai.facedb.DeletePersonRequest.Builder, com.intellif.ifai.facedb.DeletePersonRequestOrBuilder> deletionRequestBuilder_;
    /**
     * <pre>
     * 删除授权
     * </pre>
     *
     * <code>.Ifaipb.DeletePersonRequest deletion_request = 3;</code>
     */
    public boolean hasDeletionRequest() {
      return typeCase_ == 3;
    }
    /**
     * <pre>
     * 删除授权
     * </pre>
     *
     * <code>.Ifaipb.DeletePersonRequest deletion_request = 3;</code>
     */
    public com.intellif.ifai.facedb.DeletePersonRequest getDeletionRequest() {
      if (deletionRequestBuilder_ == null) {
        if (typeCase_ == 3) {
          return (com.intellif.ifai.facedb.DeletePersonRequest) type_;
        }
        return com.intellif.ifai.facedb.DeletePersonRequest.getDefaultInstance();
      } else {
        if (typeCase_ == 3) {
          return deletionRequestBuilder_.getMessage();
        }
        return com.intellif.ifai.facedb.DeletePersonRequest.getDefaultInstance();
      }
    }
    /**
     * <pre>
     * 删除授权
     * </pre>
     *
     * <code>.Ifaipb.DeletePersonRequest deletion_request = 3;</code>
     */
    public Builder setDeletionRequest(com.intellif.ifai.facedb.DeletePersonRequest value) {
      if (deletionRequestBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        type_ = value;
        onChanged();
      } else {
        deletionRequestBuilder_.setMessage(value);
      }
      typeCase_ = 3;
      return this;
    }
    /**
     * <pre>
     * 删除授权
     * </pre>
     *
     * <code>.Ifaipb.DeletePersonRequest deletion_request = 3;</code>
     */
    public Builder setDeletionRequest(
        com.intellif.ifai.facedb.DeletePersonRequest.Builder builderForValue) {
      if (deletionRequestBuilder_ == null) {
        type_ = builderForValue.build();
        onChanged();
      } else {
        deletionRequestBuilder_.setMessage(builderForValue.build());
      }
      typeCase_ = 3;
      return this;
    }
    /**
     * <pre>
     * 删除授权
     * </pre>
     *
     * <code>.Ifaipb.DeletePersonRequest deletion_request = 3;</code>
     */
    public Builder mergeDeletionRequest(com.intellif.ifai.facedb.DeletePersonRequest value) {
      if (deletionRequestBuilder_ == null) {
        if (typeCase_ == 3 &&
            type_ != com.intellif.ifai.facedb.DeletePersonRequest.getDefaultInstance()) {
          type_ = com.intellif.ifai.facedb.DeletePersonRequest.newBuilder((com.intellif.ifai.facedb.DeletePersonRequest) type_)
              .mergeFrom(value).buildPartial();
        } else {
          type_ = value;
        }
        onChanged();
      } else {
        if (typeCase_ == 3) {
          deletionRequestBuilder_.mergeFrom(value);
        }
        deletionRequestBuilder_.setMessage(value);
      }
      typeCase_ = 3;
      return this;
    }
    /**
     * <pre>
     * 删除授权
     * </pre>
     *
     * <code>.Ifaipb.DeletePersonRequest deletion_request = 3;</code>
     */
    public Builder clearDeletionRequest() {
      if (deletionRequestBuilder_ == null) {
        if (typeCase_ == 3) {
          typeCase_ = 0;
          type_ = null;
          onChanged();
        }
      } else {
        if (typeCase_ == 3) {
          typeCase_ = 0;
          type_ = null;
        }
        deletionRequestBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * 删除授权
     * </pre>
     *
     * <code>.Ifaipb.DeletePersonRequest deletion_request = 3;</code>
     */
    public com.intellif.ifai.facedb.DeletePersonRequest.Builder getDeletionRequestBuilder() {
      return getDeletionRequestFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * 删除授权
     * </pre>
     *
     * <code>.Ifaipb.DeletePersonRequest deletion_request = 3;</code>
     */
    public com.intellif.ifai.facedb.DeletePersonRequestOrBuilder getDeletionRequestOrBuilder() {
      if ((typeCase_ == 3) && (deletionRequestBuilder_ != null)) {
        return deletionRequestBuilder_.getMessageOrBuilder();
      } else {
        if (typeCase_ == 3) {
          return (com.intellif.ifai.facedb.DeletePersonRequest) type_;
        }
        return com.intellif.ifai.facedb.DeletePersonRequest.getDefaultInstance();
      }
    }
    /**
     * <pre>
     * 删除授权
     * </pre>
     *
     * <code>.Ifaipb.DeletePersonRequest deletion_request = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.intellif.ifai.facedb.DeletePersonRequest, com.intellif.ifai.facedb.DeletePersonRequest.Builder, com.intellif.ifai.facedb.DeletePersonRequestOrBuilder> 
        getDeletionRequestFieldBuilder() {
      if (deletionRequestBuilder_ == null) {
        if (!(typeCase_ == 3)) {
          type_ = com.intellif.ifai.facedb.DeletePersonRequest.getDefaultInstance();
        }
        deletionRequestBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.intellif.ifai.facedb.DeletePersonRequest, com.intellif.ifai.facedb.DeletePersonRequest.Builder, com.intellif.ifai.facedb.DeletePersonRequestOrBuilder>(
                (com.intellif.ifai.facedb.DeletePersonRequest) type_,
                getParentForChildren(),
                isClean());
        type_ = null;
      }
      typeCase_ = 3;
      onChanged();;
      return deletionRequestBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        com.intellif.ifai.facedb.SetPersonRequest, com.intellif.ifai.facedb.SetPersonRequest.Builder, com.intellif.ifai.facedb.SetPersonRequestOrBuilder> modificationRequestBuilder_;
    /**
     * <pre>
     * 修改人员信息
     * </pre>
     *
     * <code>.Ifaipb.SetPersonRequest modification_request = 4;</code>
     */
    public boolean hasModificationRequest() {
      return typeCase_ == 4;
    }
    /**
     * <pre>
     * 修改人员信息
     * </pre>
     *
     * <code>.Ifaipb.SetPersonRequest modification_request = 4;</code>
     */
    public com.intellif.ifai.facedb.SetPersonRequest getModificationRequest() {
      if (modificationRequestBuilder_ == null) {
        if (typeCase_ == 4) {
          return (com.intellif.ifai.facedb.SetPersonRequest) type_;
        }
        return com.intellif.ifai.facedb.SetPersonRequest.getDefaultInstance();
      } else {
        if (typeCase_ == 4) {
          return modificationRequestBuilder_.getMessage();
        }
        return com.intellif.ifai.facedb.SetPersonRequest.getDefaultInstance();
      }
    }
    /**
     * <pre>
     * 修改人员信息
     * </pre>
     *
     * <code>.Ifaipb.SetPersonRequest modification_request = 4;</code>
     */
    public Builder setModificationRequest(com.intellif.ifai.facedb.SetPersonRequest value) {
      if (modificationRequestBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        type_ = value;
        onChanged();
      } else {
        modificationRequestBuilder_.setMessage(value);
      }
      typeCase_ = 4;
      return this;
    }
    /**
     * <pre>
     * 修改人员信息
     * </pre>
     *
     * <code>.Ifaipb.SetPersonRequest modification_request = 4;</code>
     */
    public Builder setModificationRequest(
        com.intellif.ifai.facedb.SetPersonRequest.Builder builderForValue) {
      if (modificationRequestBuilder_ == null) {
        type_ = builderForValue.build();
        onChanged();
      } else {
        modificationRequestBuilder_.setMessage(builderForValue.build());
      }
      typeCase_ = 4;
      return this;
    }
    /**
     * <pre>
     * 修改人员信息
     * </pre>
     *
     * <code>.Ifaipb.SetPersonRequest modification_request = 4;</code>
     */
    public Builder mergeModificationRequest(com.intellif.ifai.facedb.SetPersonRequest value) {
      if (modificationRequestBuilder_ == null) {
        if (typeCase_ == 4 &&
            type_ != com.intellif.ifai.facedb.SetPersonRequest.getDefaultInstance()) {
          type_ = com.intellif.ifai.facedb.SetPersonRequest.newBuilder((com.intellif.ifai.facedb.SetPersonRequest) type_)
              .mergeFrom(value).buildPartial();
        } else {
          type_ = value;
        }
        onChanged();
      } else {
        if (typeCase_ == 4) {
          modificationRequestBuilder_.mergeFrom(value);
        }
        modificationRequestBuilder_.setMessage(value);
      }
      typeCase_ = 4;
      return this;
    }
    /**
     * <pre>
     * 修改人员信息
     * </pre>
     *
     * <code>.Ifaipb.SetPersonRequest modification_request = 4;</code>
     */
    public Builder clearModificationRequest() {
      if (modificationRequestBuilder_ == null) {
        if (typeCase_ == 4) {
          typeCase_ = 0;
          type_ = null;
          onChanged();
        }
      } else {
        if (typeCase_ == 4) {
          typeCase_ = 0;
          type_ = null;
        }
        modificationRequestBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * 修改人员信息
     * </pre>
     *
     * <code>.Ifaipb.SetPersonRequest modification_request = 4;</code>
     */
    public com.intellif.ifai.facedb.SetPersonRequest.Builder getModificationRequestBuilder() {
      return getModificationRequestFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * 修改人员信息
     * </pre>
     *
     * <code>.Ifaipb.SetPersonRequest modification_request = 4;</code>
     */
    public com.intellif.ifai.facedb.SetPersonRequestOrBuilder getModificationRequestOrBuilder() {
      if ((typeCase_ == 4) && (modificationRequestBuilder_ != null)) {
        return modificationRequestBuilder_.getMessageOrBuilder();
      } else {
        if (typeCase_ == 4) {
          return (com.intellif.ifai.facedb.SetPersonRequest) type_;
        }
        return com.intellif.ifai.facedb.SetPersonRequest.getDefaultInstance();
      }
    }
    /**
     * <pre>
     * 修改人员信息
     * </pre>
     *
     * <code>.Ifaipb.SetPersonRequest modification_request = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.intellif.ifai.facedb.SetPersonRequest, com.intellif.ifai.facedb.SetPersonRequest.Builder, com.intellif.ifai.facedb.SetPersonRequestOrBuilder> 
        getModificationRequestFieldBuilder() {
      if (modificationRequestBuilder_ == null) {
        if (!(typeCase_ == 4)) {
          type_ = com.intellif.ifai.facedb.SetPersonRequest.getDefaultInstance();
        }
        modificationRequestBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.intellif.ifai.facedb.SetPersonRequest, com.intellif.ifai.facedb.SetPersonRequest.Builder, com.intellif.ifai.facedb.SetPersonRequestOrBuilder>(
                (com.intellif.ifai.facedb.SetPersonRequest) type_,
                getParentForChildren(),
                isClean());
        type_ = null;
      }
      typeCase_ = 4;
      onChanged();;
      return modificationRequestBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        com.intellif.ifai.facedb.AddPersonRequest, com.intellif.ifai.facedb.AddPersonRequest.Builder, com.intellif.ifai.facedb.AddPersonRequestOrBuilder> imageRequestBuilder_;
    /**
     * <pre>
     * 人脸照片授权
     * </pre>
     *
     * <code>.Ifaipb.AddPersonRequest image_request = 5;</code>
     */
    public boolean hasImageRequest() {
      return typeCase_ == 5;
    }
    /**
     * <pre>
     * 人脸照片授权
     * </pre>
     *
     * <code>.Ifaipb.AddPersonRequest image_request = 5;</code>
     */
    public com.intellif.ifai.facedb.AddPersonRequest getImageRequest() {
      if (imageRequestBuilder_ == null) {
        if (typeCase_ == 5) {
          return (com.intellif.ifai.facedb.AddPersonRequest) type_;
        }
        return com.intellif.ifai.facedb.AddPersonRequest.getDefaultInstance();
      } else {
        if (typeCase_ == 5) {
          return imageRequestBuilder_.getMessage();
        }
        return com.intellif.ifai.facedb.AddPersonRequest.getDefaultInstance();
      }
    }
    /**
     * <pre>
     * 人脸照片授权
     * </pre>
     *
     * <code>.Ifaipb.AddPersonRequest image_request = 5;</code>
     */
    public Builder setImageRequest(com.intellif.ifai.facedb.AddPersonRequest value) {
      if (imageRequestBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        type_ = value;
        onChanged();
      } else {
        imageRequestBuilder_.setMessage(value);
      }
      typeCase_ = 5;
      return this;
    }
    /**
     * <pre>
     * 人脸照片授权
     * </pre>
     *
     * <code>.Ifaipb.AddPersonRequest image_request = 5;</code>
     */
    public Builder setImageRequest(
        com.intellif.ifai.facedb.AddPersonRequest.Builder builderForValue) {
      if (imageRequestBuilder_ == null) {
        type_ = builderForValue.build();
        onChanged();
      } else {
        imageRequestBuilder_.setMessage(builderForValue.build());
      }
      typeCase_ = 5;
      return this;
    }
    /**
     * <pre>
     * 人脸照片授权
     * </pre>
     *
     * <code>.Ifaipb.AddPersonRequest image_request = 5;</code>
     */
    public Builder mergeImageRequest(com.intellif.ifai.facedb.AddPersonRequest value) {
      if (imageRequestBuilder_ == null) {
        if (typeCase_ == 5 &&
            type_ != com.intellif.ifai.facedb.AddPersonRequest.getDefaultInstance()) {
          type_ = com.intellif.ifai.facedb.AddPersonRequest.newBuilder((com.intellif.ifai.facedb.AddPersonRequest) type_)
              .mergeFrom(value).buildPartial();
        } else {
          type_ = value;
        }
        onChanged();
      } else {
        if (typeCase_ == 5) {
          imageRequestBuilder_.mergeFrom(value);
        }
        imageRequestBuilder_.setMessage(value);
      }
      typeCase_ = 5;
      return this;
    }
    /**
     * <pre>
     * 人脸照片授权
     * </pre>
     *
     * <code>.Ifaipb.AddPersonRequest image_request = 5;</code>
     */
    public Builder clearImageRequest() {
      if (imageRequestBuilder_ == null) {
        if (typeCase_ == 5) {
          typeCase_ = 0;
          type_ = null;
          onChanged();
        }
      } else {
        if (typeCase_ == 5) {
          typeCase_ = 0;
          type_ = null;
        }
        imageRequestBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * 人脸照片授权
     * </pre>
     *
     * <code>.Ifaipb.AddPersonRequest image_request = 5;</code>
     */
    public com.intellif.ifai.facedb.AddPersonRequest.Builder getImageRequestBuilder() {
      return getImageRequestFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * 人脸照片授权
     * </pre>
     *
     * <code>.Ifaipb.AddPersonRequest image_request = 5;</code>
     */
    public com.intellif.ifai.facedb.AddPersonRequestOrBuilder getImageRequestOrBuilder() {
      if ((typeCase_ == 5) && (imageRequestBuilder_ != null)) {
        return imageRequestBuilder_.getMessageOrBuilder();
      } else {
        if (typeCase_ == 5) {
          return (com.intellif.ifai.facedb.AddPersonRequest) type_;
        }
        return com.intellif.ifai.facedb.AddPersonRequest.getDefaultInstance();
      }
    }
    /**
     * <pre>
     * 人脸照片授权
     * </pre>
     *
     * <code>.Ifaipb.AddPersonRequest image_request = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.intellif.ifai.facedb.AddPersonRequest, com.intellif.ifai.facedb.AddPersonRequest.Builder, com.intellif.ifai.facedb.AddPersonRequestOrBuilder> 
        getImageRequestFieldBuilder() {
      if (imageRequestBuilder_ == null) {
        if (!(typeCase_ == 5)) {
          type_ = com.intellif.ifai.facedb.AddPersonRequest.getDefaultInstance();
        }
        imageRequestBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.intellif.ifai.facedb.AddPersonRequest, com.intellif.ifai.facedb.AddPersonRequest.Builder, com.intellif.ifai.facedb.AddPersonRequestOrBuilder>(
                (com.intellif.ifai.facedb.AddPersonRequest) type_,
                getParentForChildren(),
                isClean());
        type_ = null;
      }
      typeCase_ = 5;
      onChanged();;
      return imageRequestBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:Ifaipb.FaceCommand)
  }

  // @@protoc_insertion_point(class_scope:Ifaipb.FaceCommand)
  private static final com.intellif.ifai.facedb.FaceCommand DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.intellif.ifai.facedb.FaceCommand();
  }

  public static com.intellif.ifai.facedb.FaceCommand getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<FaceCommand>
      PARSER = new com.google.protobuf.AbstractParser<FaceCommand>() {
    @java.lang.Override
    public FaceCommand parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new FaceCommand(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<FaceCommand> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<FaceCommand> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.intellif.ifai.facedb.FaceCommand getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

