// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: IfFaceDatabase.proto

package com.intellif.ifai.facedb;

public interface PullFaceRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Ifaipb.PullFaceRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 拉取id
   * </pre>
   *
   * <code>int32 pull_id = 1;</code>
   */
  int getPullId();

  /**
   * <pre>
   * 拉取开始位置
   * </pre>
   *
   * <code>int32 pull_begin = 2;</code>
   */
  int getPullBegin();

  /**
   * <pre>
   * 拉取数量
   * </pre>
   *
   * <code>int32 pull_size = 3;</code>
   */
  int getPullSize();
}
